import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import importX from 'eslint-plugin-import-x';
import unusedImports from 'eslint-plugin-unused-imports';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  // Ignore patterns
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/*.js',
      '**/*.cjs',
      '**/*.mjs',
      'e2e/**',
      // Schema artefacts regenerated by `pnpm schemas:build` — multi-hundred-MB
      // generated TypeScript that has no business being linted, formatted, or
      // type-checked alongside hand-written source. Mirror of .gitignore.
      'packages/core/src/schemas/generated/**',
    ],
  },

  // Base JS rules
  js.configs.recommended,

  // TypeScript rules
  ...tseslint.configs.recommended,

  // Project rules
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: {
      'import-x': importX,
      'unused-imports': unusedImports,
      'react-hooks': reactHooks,
    },
    rules: {
      // ── Unused imports: auto-remove ──
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          varsIgnorePattern: '^_',
          args: 'after-used',
          argsIgnorePattern: '^_',
        },
      ],

      // ── Import order (warn — cosmetic, auto-fixable) ──
      'import-x/order': [
        'warn',
        {
          groups: ['builtin', 'external', 'internal', ['parent', 'sibling', 'index'], 'type'],
          'newlines-between': 'never',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import-x/no-duplicates': 'error',
      'import-x/no-useless-path-segments': ['error', { noUselessIndex: true }],

      // ── React hooks ──
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // ── Relax noisy rules for existing codebase ──
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'prefer-const': 'warn',
    },
    settings: {
      'import-x/resolver': {
        node: true,
      },
    },
  },

  // Test-file relaxations
  {
    files: ['**/__tests__/**/*.{ts,tsx}', '**/*.test.{ts,tsx}'],
    rules: {
      // `vi.mock(...)` is hoisted by vitest, so tests deliberately
      // interleave mock statements with imports. The import-order rule
      // can't reason about hoisting and flags the perfectly-valid
      // pattern as out-of-order. Disable for tests only — source files
      // still get the order check.
      'import-x/order': 'off',
      // Tests routinely destructure helper return values to assert on a
      // subset; the remaining fields aren't "unused" — they're part of
      // the shape contract. Silence for tests; source files still get
      // the check (prefix unused with `_` to opt out per-case).
      'unused-imports/no-unused-vars': 'off',
    },
  },
);
