/**
 * High-level resource category: COMPUTE.
 *
 * Web apps, APIs, services, serverless functions, containers, scheduled tasks.
 *
 * SIZE EXCEPTION: this file is intentionally >500 LOC because it is dominated
 * by data — the per-resource property catalogues, instance-size pickers, and
 * provider implementations together total ~1780 LOC of pure literal. Splitting
 * further would fragment the data without improving readability.
 *
 * The exported `compute: HighLevelCategory` is consumed by `../high-level-resources.ts`
 * which assembles it into `HIGH_LEVEL_CATEGORIES`. The shape and content are
 * byte-identical to what was previously inlined there.
 */

// `NodeBehavior` is imported because the data literal uses `behavior: '...' as NodeBehavior` casts.
import type { HighLevelCategory, NodeBehavior } from '../types';
export type { NodeBehavior };

export const compute: HighLevelCategory = 
  {
    id: 'compute',
    name: 'Compute',
    description: 'Web apps, APIs, and services',
    icon: 'Globe',
    resources: [
      {
        id: 'frontend-app',
        name: 'Frontend App',
        description: 'Static website or single-page application with CDN',
        icon: 'Layout',
        category: 'compute',
        behavior: 'singleton' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          {
            provider: 'aws',
            resource_type: 'aws:s3:BucketWebsiteConfiguration',
            display_name: 'S3 Static Website',
          },
          {
            provider: 'gcp',
            resource_type: 'gcp:firebase:Hosting',
            display_name: 'Firebase Hosting',
          },
          {
            provider: 'azure',
            resource_type: 'azure:storage:StaticWebsite',
            display_name: 'Azure Static Web App',
          },
        ],
        keywords: ['static', 'website', 's3', 'bucket', 'cloudfront', 'cdn', 'blob', 'storage'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this website',
            placeholder: 'My Website',
          },
          {
            name: 'size',
            label: 'Hosting tier',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Hosting plan — determines build minutes, bandwidth, and features',
            default: 'amplify-free',
            optionDetails: [
              {
                value: 'amplify-free',
                label: 'Amplify Free',
                description: '1,000 build min · 15 GB served/mo',
                cost: 'Free',
                provider: 'aws',
              },
              {
                value: 'amplify-standard',
                label: 'Amplify Standard',
                description: 'Unlimited builds · pay per GB',
                cost: '~$0.15/GB served',
                provider: 'aws',
              },
              {
                value: 'firebase-free',
                label: 'Spark (Free)',
                description: '10 GB hosting · 360 MB/day served',
                cost: 'Free',
                provider: 'gcp',
              },
              {
                value: 'firebase-blaze',
                label: 'Blaze (Pay-as-you-go)',
                description: 'Unlimited hosting · pay per GB',
                cost: '~$0.15/GB served',
                provider: 'gcp',
              },
              {
                value: 'azure-free',
                label: 'Free',
                description: '100 MB storage · 0.5 GB bandwidth',
                cost: 'Free',
                provider: 'azure',
              },
              {
                value: 'azure-standard',
                label: 'Standard',
                description: '250 MB storage · 100 GB bandwidth',
                cost: '~$9/mo',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'framework',
            label: 'Framework',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'What framework is your site built with?',
            default: 'react',
            optionDetails: [
              { value: 'react', label: 'React', description: 'Component-based SPA' },
              { value: 'vue', label: 'Vue', description: 'Progressive framework' },
              { value: 'angular', label: 'Angular', description: 'Enterprise SPA framework' },
              { value: 'nextjs', label: 'Next.js', description: 'React with SSR/SSG' },
              { value: 'astro', label: 'Astro', description: 'Content-focused, zero JS by default' },
              { value: 'svelte', label: 'Svelte', description: 'Compiled framework, small bundles' },
              { value: 'static', label: 'Static HTML', description: 'Plain HTML/CSS/JS' },
            ],
          },
          {
            name: 'custom_domain',
            label: 'Custom domain',
            type: 'string',
            required: false,
            tier: 'detailed',
            description: 'Use your own domain name instead of the default one',
            placeholder: 'e.g. app.example.com',
          },
          {
            name: 'fast_worldwide',
            label: 'Fast worldwide loading?',
            type: 'boolean',
            required: false,
            tier: 'detailed',
            description: 'Caches your site on servers around the world so visitors everywhere get fast load times',
            default: true,
          },
        ],
      },
      {
        id: 'backend-api',
        name: 'Backend API',
        description: 'REST or GraphQL API service',
        icon: 'Server',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure', 'kubernetes'],
        implementations: [
          { provider: 'aws', resource_type: 'aws:apigatewayv2:Api', display_name: 'API Gateway' },
          { provider: 'gcp', resource_type: 'gcp:cloudrun:Service', display_name: 'Cloud Run' },
          {
            provider: 'azure',
            resource_type: 'azure:apimanagement:Api',
            display_name: 'API Management',
          },
          {
            provider: 'kubernetes',
            resource_type: 'kubernetes:apps/v1:Deployment',
            display_name: 'K8s Deployment',
          },
        ],
        keywords: ['api', 'gateway', 'lambda', 'function', 'app', 'service', 'ecs', 'container'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this API',
            placeholder: 'My API',
          },
          {
            name: 'size',
            label: 'Container size',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'CPU and memory allocation per container',
            default: '0.25-512',
            optionDetails: [
              {
                value: '0.25-512',
                label: '0.25 vCPU / 512 MB',
                description: 'Lightweight APIs',
                cost: '~$9/mo',
                provider: 'aws',
              },
              {
                value: '0.5-1024',
                label: '0.5 vCPU / 1 GB',
                description: 'Light workloads',
                cost: '~$18/mo',
                provider: 'aws',
              },
              {
                value: '1-2048',
                label: '1 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$36/mo',
                provider: 'aws',
              },
              {
                value: '2-4096',
                label: '2 vCPU / 4 GB',
                description: 'Heavy workloads',
                cost: '~$73/mo',
                provider: 'aws',
              },
              {
                value: '4-8192',
                label: '4 vCPU / 8 GB',
                description: 'Compute-intensive',
                cost: '~$146/mo',
                provider: 'aws',
              },
              {
                value: 'gcp-1-512',
                label: '1 vCPU / 512 MB',
                description: 'Cloud Run minimum',
                cost: '~$10/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-2-1024',
                label: '2 vCPU / 1 GB',
                description: 'Light workloads',
                cost: '~$25/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-4-2048',
                label: '4 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$50/mo',
                provider: 'gcp',
              },
              {
                value: 'azure-0.25-0.5',
                label: '0.25 vCPU / 0.5 GB',
                description: 'Container Apps minimum',
                cost: '~$5/mo',
                provider: 'azure',
              },
              {
                value: 'azure-0.5-1',
                label: '0.5 vCPU / 1 GB',
                description: 'Light workloads',
                cost: '~$15/mo',
                provider: 'azure',
              },
              {
                value: 'azure-1-2',
                label: '1 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$36/mo',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Language runtime for your API',
            default: 'nodejs22',
            optionDetails: [
              { value: 'nodejs22', label: 'Node.js 22', description: 'Latest LTS (recommended)' },
              { value: 'nodejs20', label: 'Node.js 20', description: 'Previous LTS' },
              { value: 'python3.12', label: 'Python 3.12', description: 'Latest stable' },
              { value: 'go1.22', label: 'Go 1.22', description: 'Latest stable' },
              { value: 'java21', label: 'Java 21', description: 'Latest LTS' },
              { value: 'dotnet8', label: '.NET 8', description: 'Latest LTS' },
              { value: 'ruby3.3', label: 'Ruby 3.3', description: 'Latest stable' },
            ],
          },
          {
            name: 'login_required',
            label: 'Require login?',
            type: 'select',
            required: false,
            tier: 'detailed',
            description: 'How should users prove who they are?',
            options: [
              'No login needed',
              'API key',
              'Username & password tokens',
              'Social login (Google, GitHub, etc.)',
            ],
            default: 'No login needed',
          },
          {
            name: 'minInstances',
            label: 'Min instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Minimum number of always-running instances (0 = scale to zero)',
            default: 1,
          },
          {
            name: 'maxInstances',
            label: 'Max instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Maximum number of instances during peak traffic',
            default: 3,
          },
          {
            name: 'scalingMetric',
            label: 'Scale on',
            type: 'select',
            required: false,
            tier: 'detailed',
            description: 'What metric triggers scaling',
            options: ['cpu', 'memory', 'requests', 'concurrency'],
            default: 'cpu',
          },
          {
            name: 'scalingThreshold',
            label: 'Threshold (%)',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Scale up when the metric exceeds this percentage',
            default: 70,
          },
        ],
      },
      {
        id: 'serverless-function',
        name: 'Serverless Function',
        description: 'Event-driven function that scales automatically',
        icon: 'Zap',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          {
            provider: 'aws',
            resource_type: 'aws:lambda:Function',
            display_name: 'Lambda Function',
          },
          {
            provider: 'gcp',
            resource_type: 'gcp:cloudfunctions:Function',
            display_name: 'Cloud Function',
          },
          {
            provider: 'azure',
            resource_type: 'azure:web:Function',
            display_name: 'Azure Function',
          },
        ],
        keywords: ['lambda', 'function', 'serverless', 'cloud function'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this function',
            placeholder: 'My Function',
          },
          {
            name: 'memory',
            label: 'Memory',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Memory allocation — also determines proportional CPU',
            default: '128',
            tooltip:
              'AWS Lambda: 128 MB – 10,240 MB (10 GB) in 1 MB increments. CPU scales proportionally — at 1,769 MB you get 1 full vCPU, at 10,240 MB you get 6 vCPUs. GCP Cloud Functions: 128 MB – 32 GB (2nd gen). Azure Functions: up to 14 GB (Premium plan).',
            optionDetails: [
              {
                value: '128',
                label: '128 MB',
                description: 'Minimum — quick tasks',
                cost: '~$0.01/M invocations',
                provider: 'aws',
                tooltip: 'Smallest Lambda size. ~0.07 vCPU proportional. Good for simple API responses.',
              },
              { value: '256', label: '256 MB', description: 'Light processing', cost: '~$0.02/M', provider: 'aws' },
              { value: '512', label: '512 MB', description: 'Standard workloads', cost: '~$0.04/M', provider: 'aws' },
              { value: '1024', label: '1024 MB', description: 'Heavy processing', cost: '~$0.08/M', provider: 'aws' },
              {
                value: '1769',
                label: '1769 MB (1 vCPU)',
                description: 'Full vCPU threshold',
                cost: '~$0.14/M',
                provider: 'aws',
                tooltip: 'At 1,769 MB you get exactly 1 full vCPU. Best price/performance for CPU-bound work.',
              },
              { value: '2048', label: '2048 MB', description: 'Compute-intensive', cost: '~$0.17/M', provider: 'aws' },
              {
                value: '3072',
                label: '3072 MB',
                description: 'Heavy compute · ~1.7 vCPU',
                cost: '~$0.25/M',
                provider: 'aws',
              },
              {
                value: '4096',
                label: '4096 MB',
                description: 'Very heavy · ~2.3 vCPU',
                cost: '~$0.33/M',
                provider: 'aws',
              },
              {
                value: '8192',
                label: '8192 MB',
                description: 'Maximum compute · ~4.6 vCPU',
                cost: '~$0.67/M',
                provider: 'aws',
              },
              {
                value: '10240',
                label: '10240 MB (max)',
                description: 'Lambda maximum · 6 vCPU',
                cost: '~$0.83/M',
                provider: 'aws',
                tooltip: 'Maximum Lambda memory. Provides 6 vCPUs. Use for ML inference, video processing, etc.',
              },
              { value: '128-200mhz', label: '128 MB / 200 MHz', description: 'Minimum tier', provider: 'gcp' },
              { value: '256-400mhz', label: '256 MB / 400 MHz', description: 'Light processing', provider: 'gcp' },
              { value: '512-800mhz', label: '512 MB / 800 MHz', description: 'Standard workloads', provider: 'gcp' },
              { value: '1024-1400mhz', label: '1024 MB / 1.4 GHz', description: 'Heavy processing', provider: 'gcp' },
              { value: '2048-2800mhz', label: '2048 MB / 2.8 GHz', description: 'Compute-intensive', provider: 'gcp' },
              { value: '4096-4800mhz', label: '4096 MB / 4.8 GHz', description: 'Very heavy compute', provider: 'gcp' },
              { value: '8192-4800mhz', label: '8192 MB / 4.8 GHz', description: 'Maximum (1st gen)', provider: 'gcp' },
              {
                value: '16384-gcp',
                label: '16 GB',
                description: '2nd gen only · high-memory',
                provider: 'gcp',
                tooltip: 'Requires Cloud Functions 2nd gen (Cloud Run based)',
              },
              {
                value: '32768-gcp',
                label: '32 GB (max)',
                description: '2nd gen maximum',
                provider: 'gcp',
                tooltip: 'Maximum memory for Cloud Functions 2nd gen',
              },
              { value: 'custom', label: 'Custom', description: 'Enter memory (128–10,240 MB)', provider: 'aws' },
              { value: 'custom', label: 'Custom', description: 'Enter memory (128–32,768 MB)', provider: 'gcp' },
              { value: 'custom', label: 'Custom', description: 'Enter memory (128–14,336 MB)', provider: 'azure' },
            ],
            customInput: { type: 'number', unit: 'MB', min: 128, max: 32768, step: 64, placeholder: 'e.g. 1536' },
          },
          {
            name: 'timeout',
            label: 'Timeout',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Maximum execution time before the function is killed',
            default: '3',
            tooltip:
              'AWS Lambda: 1–900s (15 min). GCP Cloud Functions: 60s (1st gen), 3,600s (2nd gen). Azure Functions: 300s (Consumption), 1,800s (Premium).',
            optionDetails: [
              // AWS Lambda: 1–900 seconds
              { value: '3', label: '3 seconds', description: 'Default — fast API responses', provider: 'aws' },
              { value: '10', label: '10 seconds', description: 'Quick processing', provider: 'aws' },
              { value: '30', label: '30 seconds', description: 'Moderate processing', provider: 'aws' },
              { value: '60', label: '60 seconds', description: 'File processing / transforms', provider: 'aws' },
              { value: '300', label: '5 minutes', description: 'Heavy batch work', provider: 'aws' },
              { value: '900', label: '15 minutes', description: 'Maximum', provider: 'aws' },
              { value: 'custom', label: 'Custom', description: 'Enter timeout (1–900s)', provider: 'aws' },
              // GCP Cloud Functions: up to 60 minutes (2nd gen)
              { value: '60', label: '60 seconds', description: '1st gen default maximum', provider: 'gcp' },
              { value: '300', label: '5 minutes', description: 'Standard processing', provider: 'gcp' },
              { value: '540', label: '9 minutes', description: 'Extended processing', provider: 'gcp' },
              { value: '900', label: '15 minutes', description: 'Heavy processing', provider: 'gcp' },
              { value: '1800', label: '30 minutes', description: '2nd gen — long-running', provider: 'gcp' },
              { value: '3600', label: '60 minutes', description: '2nd gen maximum', provider: 'gcp' },
              { value: 'custom', label: 'Custom', description: 'Enter timeout (1–3,600s)', provider: 'gcp' },
              // Azure Functions: depends on plan
              { value: '30', label: '30 seconds', description: 'Quick processing', provider: 'azure' },
              { value: '300', label: '5 minutes', description: 'Consumption plan default max', provider: 'azure' },
              { value: '600', label: '10 minutes', description: 'Consumption plan extended max', provider: 'azure' },
              { value: '1800', label: '30 minutes', description: 'Premium plan maximum', provider: 'azure' },
              { value: 'custom', label: 'Custom', description: 'Enter timeout (1–1,800s)', provider: 'azure' },
            ],
            customInput: { type: 'number', unit: 'seconds', min: 1, max: 3600, step: 1, placeholder: 'e.g. 120' },
          },
          {
            name: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Language runtime for your function code',
            default: 'nodejs22.x',
            optionDetails: [
              { value: 'nodejs22.x', label: 'Node.js 22', description: 'Latest LTS (recommended)' },
              { value: 'nodejs20.x', label: 'Node.js 20', description: 'Previous LTS — widely supported' },
              { value: 'python3.12', label: 'Python 3.12', description: 'Latest stable' },
              { value: 'python3.11', label: 'Python 3.11', description: 'Previous stable' },
              { value: 'go1.x', label: 'Go 1.x', description: 'Fast cold starts' },
              { value: 'java21', label: 'Java 21', description: 'Latest LTS' },
              { value: 'java17', label: 'Java 17', description: 'Previous LTS' },
              { value: 'dotnet8', label: '.NET 8', description: 'Latest LTS' },
              { value: 'ruby3.3', label: 'Ruby 3.3', description: 'Latest stable' },
            ],
          },
        ],
      },
      {
        id: 'function-compute',
        name: 'Function Compute',
        description: 'Alibaba Cloud serverless functions with event-driven execution',
        icon: 'Zap',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['alibaba'],
        implementations: [
          {
            provider: 'alibaba',
            resource_type: 'alibaba:fc:Function',
            display_name: 'Function Compute',
          },
        ],
        keywords: ['function', 'compute', 'serverless', 'alibaba', 'fc'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this function',
            placeholder: 'My Function',
          },
          {
            name: 'memory',
            label: 'Memory',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Memory allocation — also determines proportional CPU',
            default: '512',
            optionDetails: [
              {
                value: '128',
                label: '128 MB',
                description: 'Minimum — quick tasks',
                cost: '~$0.01/M invocations',
                provider: 'alibaba',
              },
              { value: '256', label: '256 MB', description: 'Light processing', cost: '~$0.02/M', provider: 'alibaba' },
              {
                value: '512',
                label: '512 MB',
                description: 'Standard workloads',
                cost: '~$0.04/M',
                provider: 'alibaba',
              },
              {
                value: '1024',
                label: '1024 MB',
                description: 'Heavy processing',
                cost: '~$0.08/M',
                provider: 'alibaba',
              },
              {
                value: '3072',
                label: '3072 MB',
                description: 'Compute-intensive',
                cost: '~$0.24/M',
                provider: 'alibaba',
              },
            ],
          },
          {
            name: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Language runtime for your function',
            default: 'nodejs18',
            optionDetails: [
              { value: 'nodejs18', label: 'Node.js 18', description: 'Latest supported LTS' },
              { value: 'nodejs16', label: 'Node.js 16', description: 'Previous LTS' },
              { value: 'python3.10', label: 'Python 3.10', description: 'Latest stable' },
              { value: 'python3.9', label: 'Python 3.9', description: 'Previous stable' },
              { value: 'java11', label: 'Java 11', description: 'LTS' },
              { value: 'java17', label: 'Java 17', description: 'Latest LTS' },
              { value: 'go1.x', label: 'Go', description: 'Latest stable' },
            ],
          },
        ],
      },
      {
        id: 'oci-functions',
        name: 'OCI Functions',
        description: 'Oracle Cloud serverless functions based on Fn Project',
        icon: 'Zap',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['oci'],
        implementations: [
          {
            provider: 'oci',
            resource_type: 'oci:functions:Function',
            display_name: 'OCI Function',
          },
        ],
        keywords: ['functions', 'serverless', 'oci', 'oracle', 'fn'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this function',
            placeholder: 'My Function',
          },
          {
            name: 'memory',
            label: 'Memory',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Memory allocation for function execution',
            default: '256',
            optionDetails: [
              {
                value: '128',
                label: '128 MB',
                description: 'Minimum — simple tasks',
                cost: '~2M free invocations/mo',
                provider: 'oci',
              },
              { value: '256', label: '256 MB', description: 'Light processing', provider: 'oci' },
              { value: '512', label: '512 MB', description: 'Standard workloads', provider: 'oci' },
              { value: '1024', label: '1024 MB', description: 'Heavy processing', provider: 'oci' },
              { value: '2048', label: '2048 MB', description: 'Compute-intensive (max)', provider: 'oci' },
            ],
          },
          {
            name: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Language runtime (Fn Project based)',
            default: 'java17-jdk',
            optionDetails: [
              { value: 'java17-jdk', label: 'Java 17', description: 'Latest supported LTS' },
              { value: 'java11-jdk', label: 'Java 11', description: 'Previous LTS' },
              { value: 'python3.11', label: 'Python 3.11', description: 'Latest stable' },
              { value: 'python3.9', label: 'Python 3.9', description: 'Previous stable' },
              { value: 'nodejs18', label: 'Node.js 18', description: 'Latest supported' },
              { value: 'go1.21', label: 'Go 1.21', description: 'Latest stable' },
              { value: 'ruby3.1', label: 'Ruby 3.1', description: 'Supported via Fn' },
            ],
          },
        ],
      },
      {
        id: 'do-app-platform',
        name: 'App Platform',
        description: 'DigitalOcean PaaS with git-push deployment',
        icon: 'Server',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['digitalocean'],
        implementations: [
          {
            provider: 'digitalocean',
            resource_type: 'digitalocean:app:App',
            display_name: 'App Platform App',
          },
        ],
        keywords: ['app', 'platform', 'paas', 'digitalocean', 'deploy'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this app',
            placeholder: 'My App',
          },
          {
            name: 'size',
            label: 'Instance size',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Container size for your app',
            default: 'basic-xxs',
            optionDetails: [
              {
                value: 'basic-xxs',
                label: 'Basic XXS',
                description: '1 vCPU · 512 MB RAM',
                cost: '~$5/mo',
                provider: 'digitalocean',
              },
              {
                value: 'basic-xs',
                label: 'Basic XS',
                description: '1 vCPU · 1 GB RAM',
                cost: '~$10/mo',
                provider: 'digitalocean',
              },
              {
                value: 'basic-s',
                label: 'Basic S',
                description: '1 vCPU · 2 GB RAM',
                cost: '~$20/mo',
                provider: 'digitalocean',
              },
              {
                value: 'pro-xs',
                label: 'Professional XS',
                description: '1 vCPU · 1 GB · auto-scale',
                cost: '~$12/mo',
                provider: 'digitalocean',
              },
              {
                value: 'pro-s',
                label: 'Professional S',
                description: '1 vCPU · 2 GB · auto-scale',
                cost: '~$25/mo',
                provider: 'digitalocean',
              },
              {
                value: 'pro-m',
                label: 'Professional M',
                description: '2 vCPU · 4 GB · auto-scale',
                cost: '~$50/mo',
                provider: 'digitalocean',
              },
            ],
          },
          {
            name: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Language runtime for your app',
            default: 'nodejs',
            optionDetails: [
              { value: 'nodejs', label: 'Node.js', description: 'Auto-detected from package.json' },
              { value: 'python', label: 'Python', description: 'Auto-detected from requirements.txt' },
              { value: 'go', label: 'Go', description: 'Auto-detected from go.mod' },
              { value: 'ruby', label: 'Ruby', description: 'Auto-detected from Gemfile' },
              { value: 'docker', label: 'Docker', description: 'Custom Dockerfile' },
            ],
          },
        ],
      },
      {
        id: 'container-service',
        name: 'Container Service',
        description: 'Dockerized application running in containers',
        icon: 'Box',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure', 'kubernetes'],
        implementations: [
          { provider: 'aws', resource_type: 'aws:ecs:Service', display_name: 'ECS Service' },
          { provider: 'gcp', resource_type: 'gcp:cloudrun:Service', display_name: 'Cloud Run' },
          {
            provider: 'azure',
            resource_type: 'azure:containerapp:ContainerApp',
            display_name: 'Container App',
          },
          {
            provider: 'kubernetes',
            resource_type: 'kubernetes:apps/v1:Deployment',
            display_name: 'K8s Deployment',
          },
        ],
        keywords: ['container', 'docker', 'ecs', 'kubernetes', 'k8s', 'fargate', 'aks', 'gke'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this service',
            placeholder: 'My Service',
          },
          {
            name: 'size',
            label: 'Container size',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'CPU and memory allocation per container',
            default: '0.25-512',
            optionDetails: [
              {
                value: '0.25-512',
                label: '0.25 vCPU / 512 MB',
                description: 'Lightweight tasks',
                cost: '~$9/mo',
                provider: 'aws',
              },
              {
                value: '0.5-1024',
                label: '0.5 vCPU / 1 GB',
                description: 'Light workloads',
                cost: '~$18/mo',
                provider: 'aws',
              },
              {
                value: '1-2048',
                label: '1 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$36/mo',
                provider: 'aws',
              },
              {
                value: '2-4096',
                label: '2 vCPU / 4 GB',
                description: 'Heavy workloads',
                cost: '~$73/mo',
                provider: 'aws',
              },
              {
                value: '4-8192',
                label: '4 vCPU / 8 GB',
                description: 'Compute-intensive',
                cost: '~$146/mo',
                provider: 'aws',
              },
              {
                value: 'gcp-1-512',
                label: '1 vCPU / 512 MB',
                description: 'Cloud Run minimum',
                cost: '~$10/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-2-1024',
                label: '2 vCPU / 1 GB',
                description: 'Light workloads',
                cost: '~$25/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-4-2048',
                label: '4 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$50/mo',
                provider: 'gcp',
              },
              {
                value: 'azure-0.25-0.5',
                label: '0.25 vCPU / 0.5 GB',
                description: 'Container Apps minimum',
                cost: '~$5/mo',
                provider: 'azure',
              },
              {
                value: 'azure-0.5-1',
                label: '0.5 vCPU / 1 GB',
                description: 'Light workloads',
                cost: '~$15/mo',
                provider: 'azure',
              },
              {
                value: 'azure-1-2',
                label: '1 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$36/mo',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'image',
            label: 'Container image',
            type: 'string',
            required: false,
            tier: 'detailed',
            description: 'The Docker image to run (leave blank if building from source)',
            placeholder: 'e.g. nginx:latest',
          },
          {
            name: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: false,
            tier: 'detailed',
            description: 'Application runtime or base image',
            default: 'nodejs22',
            optionDetails: [
              { value: 'nodejs22', label: 'Node.js 22', description: 'Latest LTS (recommended)' },
              { value: 'nodejs20', label: 'Node.js 20', description: 'Previous LTS' },
              { value: 'python3.12', label: 'Python 3.12', description: 'Latest stable' },
              { value: 'go1.22', label: 'Go 1.22', description: 'Latest stable' },
              { value: 'java21', label: 'Java 21', description: 'Latest LTS' },
              { value: 'dotnet8', label: '.NET 8', description: 'Latest LTS' },
              { value: 'rust', label: 'Rust', description: 'Systems programming' },
              { value: 'custom', label: 'Custom Docker', description: 'Bring your own Dockerfile' },
            ],
          },
          {
            name: 'env_vars',
            label: 'Environment variables',
            type: 'list',
            required: false,
            tier: 'detailed',
            description: 'Configuration values your app needs at startup',
            placeholder: 'e.g. DATABASE_URL=...',
            addLabel: 'Add a variable',
          },
          {
            name: 'minInstances',
            label: 'Min instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Minimum number of always-running instances (0 = scale to zero)',
            default: 1,
          },
          {
            name: 'maxInstances',
            label: 'Max instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Maximum number of instances during peak traffic',
            default: 3,
          },
          {
            name: 'scalingMetric',
            label: 'Scale on',
            type: 'select',
            required: false,
            tier: 'detailed',
            description: 'What metric triggers scaling',
            options: ['cpu', 'memory', 'requests', 'concurrency'],
            default: 'cpu',
          },
          {
            name: 'scalingThreshold',
            label: 'Threshold (%)',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Scale up when the metric exceeds this percentage',
            default: 70,
          },
        ],
      },
      {
        id: 'worker',
        name: 'Worker',
        description: 'Long-running background processor for queues, events, and batch jobs',
        icon: 'Cog',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure', 'kubernetes'],
        implementations: [
          { provider: 'aws', resource_type: 'aws:ecs:Service', display_name: 'ECS Task (Worker)' },
          { provider: 'gcp', resource_type: 'gcp:cloudrun:Job', display_name: 'Cloud Run Job' },
          {
            provider: 'azure',
            resource_type: 'azure:containerapp:ContainerApp',
            display_name: 'Container App Job',
          },
          {
            provider: 'kubernetes',
            resource_type: 'kubernetes:batch/v1:Job',
            display_name: 'K8s Job',
          },
        ],
        keywords: ['worker', 'consumer', 'processor', 'background', 'async', 'batch'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this worker',
            placeholder: 'My Worker',
          },
          {
            name: 'size',
            label: 'Container size',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'CPU and memory allocation per worker',
            default: '0.5-1024',
            optionDetails: [
              {
                value: '0.25-512',
                label: '0.25 vCPU / 512 MB',
                description: 'Lightweight tasks',
                cost: '~$9/mo',
                provider: 'aws',
              },
              {
                value: '0.5-1024',
                label: '0.5 vCPU / 1 GB',
                description: 'Light processing',
                cost: '~$18/mo',
                provider: 'aws',
              },
              {
                value: '1-2048',
                label: '1 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$36/mo',
                provider: 'aws',
              },
              {
                value: '2-4096',
                label: '2 vCPU / 4 GB',
                description: 'Heavy batch work',
                cost: '~$73/mo',
                provider: 'aws',
              },
              {
                value: '4-8192',
                label: '4 vCPU / 8 GB',
                description: 'Compute-intensive',
                cost: '~$146/mo',
                provider: 'aws',
              },
              {
                value: 'gcp-1-512',
                label: '1 vCPU / 512 MB',
                description: 'Cloud Run Job minimum',
                cost: '~$10/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-2-1024',
                label: '2 vCPU / 1 GB',
                description: 'Light processing',
                cost: '~$25/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-4-2048',
                label: '4 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$50/mo',
                provider: 'gcp',
              },
              {
                value: 'azure-0.5-1',
                label: '0.5 vCPU / 1 GB',
                description: 'Container Apps minimum',
                cost: '~$15/mo',
                provider: 'azure',
              },
              {
                value: 'azure-1-2',
                label: '1 vCPU / 2 GB',
                description: 'Standard workloads',
                cost: '~$36/mo',
                provider: 'azure',
              },
              {
                value: 'azure-2-4',
                label: '2 vCPU / 4 GB',
                description: 'Heavy workloads',
                cost: '~$73/mo',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Language runtime for your worker',
            default: 'nodejs22',
            optionDetails: [
              { value: 'nodejs22', label: 'Node.js 22', description: 'Latest LTS (recommended)' },
              { value: 'nodejs20', label: 'Node.js 20', description: 'Previous LTS' },
              { value: 'python3.12', label: 'Python 3.12', description: 'Latest stable' },
              { value: 'go1.22', label: 'Go 1.22', description: 'Latest stable' },
              { value: 'java21', label: 'Java 21', description: 'Latest LTS' },
              { value: 'custom', label: 'Custom Docker', description: 'Bring your own Dockerfile' },
            ],
          },
          {
            name: 'image',
            label: 'Container image',
            type: 'string',
            required: false,
            tier: 'detailed',
            description: 'Docker image to run (if using a container)',
            placeholder: 'e.g. my-worker:latest',
          },
          {
            name: 'minInstances',
            label: 'Min instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Minimum number of always-running workers',
            default: 1,
          },
          {
            name: 'maxInstances',
            label: 'Max instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Maximum number of workers during peak load',
            default: 3,
          },
          {
            name: 'scalingMetric',
            label: 'Scale on',
            type: 'select',
            required: false,
            tier: 'detailed',
            description: 'What metric triggers scaling',
            options: ['cpu', 'memory', 'queue-depth'],
            default: 'cpu',
          },
          {
            name: 'scalingThreshold',
            label: 'Threshold (%)',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Scale up when the metric exceeds this percentage',
            default: 70,
          },
        ],
      },
      {
        id: 'ssr-site',
        name: 'SSR Site',
        description: 'Server-rendered web application (Next.js, Nuxt, Remix)',
        icon: 'Monitor',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          { provider: 'aws', resource_type: 'aws:amplify:App', display_name: 'Amplify Hosting' },
          { provider: 'gcp', resource_type: 'gcp:cloudrun:Service', display_name: 'Cloud Run' },
          { provider: 'azure', resource_type: 'azure:web:AppService', display_name: 'App Service' },
        ],
        keywords: ['ssr', 'nextjs', 'nuxt', 'remix', 'sveltekit', 'server', 'rendered'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this web app',
            placeholder: 'My Web App',
          },
          {
            name: 'framework',
            label: 'Framework',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Which framework is your app built with?',
            default: 'nextjs',
            optionDetails: [
              { value: 'nextjs', label: 'Next.js', description: 'React SSR/SSG — most popular' },
              { value: 'nuxt', label: 'Nuxt', description: 'Vue SSR/SSG framework' },
              { value: 'remix', label: 'Remix', description: 'React full-stack web framework' },
              { value: 'sveltekit', label: 'SvelteKit', description: 'Svelte full-stack framework' },
              { value: 'astro', label: 'Astro', description: 'Content-focused with islands' },
            ],
          },
          {
            name: 'size',
            label: 'Hosting size',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Server resources for rendering pages',
            default: 'amplify-standard',
            optionDetails: [
              {
                value: 'amplify-standard',
                label: 'Amplify Standard',
                description: 'Managed SSR · auto-scaling',
                cost: '~$0.15/GB served',
                provider: 'aws',
              },
              {
                value: '0.5-1024',
                label: '0.5 vCPU / 1 GB',
                description: 'Light traffic',
                cost: '~$18/mo',
                provider: 'aws',
              },
              {
                value: '1-2048',
                label: '1 vCPU / 2 GB',
                description: 'Standard traffic',
                cost: '~$36/mo',
                provider: 'aws',
              },
              {
                value: '2-4096',
                label: '2 vCPU / 4 GB',
                description: 'Heavy traffic',
                cost: '~$73/mo',
                provider: 'aws',
              },
              {
                value: 'gcp-1-512',
                label: '1 vCPU / 512 MB',
                description: 'Cloud Run minimum',
                cost: '~$10/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-2-1024',
                label: '2 vCPU / 1 GB',
                description: 'Standard traffic',
                cost: '~$25/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-4-2048',
                label: '4 vCPU / 2 GB',
                description: 'Heavy traffic',
                cost: '~$50/mo',
                provider: 'gcp',
              },
              {
                value: 'azure-B1',
                label: 'B1 (1 vCPU / 1.75 GB)',
                description: 'Basic tier',
                cost: '~$13/mo',
                provider: 'azure',
              },
              {
                value: 'azure-S1',
                label: 'S1 (1 vCPU / 1.75 GB)',
                description: 'Standard · auto-scale',
                cost: '~$73/mo',
                provider: 'azure',
              },
              {
                value: 'azure-P1v3',
                label: 'P1v3 (2 vCPU / 8 GB)',
                description: 'Premium · high perf',
                cost: '~$138/mo',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'custom_domain',
            label: 'Custom domain',
            type: 'string',
            required: false,
            tier: 'detailed',
            description: 'Use your own domain name instead of the default one',
            placeholder: 'e.g. www.example.com',
          },
          {
            name: 'minInstances',
            label: 'Min instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Minimum number of always-running instances (0 = scale to zero)',
            default: 1,
          },
          {
            name: 'maxInstances',
            label: 'Max instances',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Maximum number of instances during peak traffic',
            default: 3,
          },
          {
            name: 'scalingMetric',
            label: 'Scale on',
            type: 'select',
            required: false,
            tier: 'detailed',
            description: 'What metric triggers scaling',
            options: ['cpu', 'memory', 'requests', 'concurrency'],
            default: 'cpu',
          },
          {
            name: 'scalingThreshold',
            label: 'Threshold (%)',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Scale up when the metric exceeds this percentage',
            default: 70,
          },
        ],
      },
      {
        id: 'scheduled-task',
        name: 'Scheduled Task',
        description: 'Run code on a schedule (cron jobs)',
        icon: 'Clock',
        category: 'compute',
        behavior: 'singleton' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          {
            provider: 'aws',
            resource_type: 'aws:scheduler:Schedule',
            display_name: 'EventBridge Scheduler',
          },
          {
            provider: 'gcp',
            resource_type: 'gcp:cloudscheduler:Job',
            display_name: 'Cloud Scheduler',
          },
          {
            provider: 'azure',
            resource_type: 'azure:logic:Workflow',
            display_name: 'Logic App Schedule',
          },
        ],
        keywords: ['cron', 'schedule', 'scheduler', 'timer', 'job', 'task', 'periodic'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this task',
            placeholder: 'Nightly Report',
          },
          {
            name: 'frequency',
            label: 'How often should this run?',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Pick a schedule. Choose Custom to type your own cron expression.',
            options: [
              'Every 5 minutes',
              'Every 15 minutes',
              'Every 30 minutes',
              'Every hour',
              'Every 6 hours',
              'Every 12 hours',
              'Daily at midnight',
              'Daily at 9 AM',
              'Weekdays at 9 AM',
              'Weekly on Monday',
              'Monthly on the 1st',
              'Custom',
            ],
            default: 'Daily at midnight',
          },
          {
            name: 'schedule_expression',
            label: 'Cron expression',
            type: 'string',
            required: false,
            tier: 'essential',
            description: 'A standard 5-field cron expression. Required when frequency is set to Custom.',
            placeholder: '0 9 * * MON-FRI',
            visibleWhen: { field: 'frequency', equals: 'Custom' },
          },
          {
            name: 'timezone',
            label: 'Timezone',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Which timezone should the schedule follow?',
            default: 'UTC',
            optionDetails: [
              { value: 'UTC', label: 'UTC', description: 'Coordinated Universal Time' },
              { value: 'US/Eastern', label: 'US/Eastern', description: 'New York (EST/EDT)' },
              { value: 'US/Pacific', label: 'US/Pacific', description: 'Los Angeles (PST/PDT)' },
              { value: 'Europe/London', label: 'Europe/London', description: 'London (GMT/BST)' },
              { value: 'Europe/Berlin', label: 'Europe/Berlin', description: 'Berlin (CET/CEST)' },
              { value: 'Asia/Tokyo', label: 'Asia/Tokyo', description: 'Tokyo (JST)' },
              { value: 'Asia/Shanghai', label: 'Asia/Shanghai', description: 'Shanghai (CST)' },
              { value: 'Australia/Sydney', label: 'Australia/Sydney', description: 'Sydney (AEST/AEDT)' },
            ],
          },
        ],
      },
      {
        id: 'llm-gateway',
        name: 'LLM Gateway',
        description: 'Proxy and route LLM API calls with rate limiting and fallbacks',
        icon: 'BrainCircuit',
        category: 'compute',
        behavior: 'connector' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          {
            provider: 'aws',
            resource_type: 'aws:bedrock:InferenceProfile',
            display_name: 'Bedrock',
          },
          {
            provider: 'gcp',
            resource_type: 'gcp:aiplatform:Endpoint',
            display_name: 'Vertex AI Endpoint',
          },
          {
            provider: 'azure',
            resource_type: 'azure:cognitiveservices:Account',
            display_name: 'Azure OpenAI',
          },
        ],
        keywords: ['llm', 'openai', 'bedrock', 'anthropic', 'ai', 'gpt', 'claude', 'inference'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this AI gateway',
            placeholder: 'My AI Gateway',
          },
          {
            name: 'model',
            label: 'Primary model',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Default LLM model to route requests to',
            default: 'claude-sonnet',
            optionDetails: [
              {
                value: 'claude-sonnet',
                label: 'Claude Sonnet',
                description: 'Fast, balanced — great for most tasks',
                cost: '~$3/$15 per M tokens in/out',
                provider: 'aws',
              },
              {
                value: 'claude-opus',
                label: 'Claude Opus',
                description: 'Most capable — complex reasoning',
                cost: '~$15/$75 per M tokens in/out',
                provider: 'aws',
              },
              {
                value: 'claude-haiku',
                label: 'Claude Haiku',
                description: 'Fastest, cheapest — simple tasks',
                cost: '~$0.25/$1.25 per M tokens in/out',
                provider: 'aws',
              },
              {
                value: 'gpt-4o',
                label: 'GPT-4o',
                description: 'OpenAI flagship — multimodal',
                cost: '~$2.50/$10 per M tokens in/out',
              },
              {
                value: 'gpt-4o-mini',
                label: 'GPT-4o mini',
                description: 'OpenAI fast — cost-efficient',
                cost: '~$0.15/$0.60 per M tokens in/out',
              },
              {
                value: 'gemini-pro',
                label: 'Gemini 2.5 Pro',
                description: 'Google flagship — long context',
                cost: '~$1.25/$10 per M tokens in/out',
                provider: 'gcp',
              },
              {
                value: 'gemini-flash',
                label: 'Gemini 2.5 Flash',
                description: 'Google fast — cost-efficient',
                cost: '~$0.15/$0.60 per M tokens in/out',
                provider: 'gcp',
              },
              {
                value: 'azure-gpt-4o',
                label: 'Azure OpenAI GPT-4o',
                description: 'GPT-4o via Azure endpoint',
                cost: '~$2.50/$10 per M tokens in/out',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'providers',
            label: 'AI providers',
            type: 'list',
            required: false,
            tier: 'detailed',
            description: 'Which AI providers should this gateway connect to?',
            placeholder: 'e.g. OpenAI, Anthropic, Google',
            addLabel: 'Add a provider',
          },
          {
            name: 'fallback',
            label: 'Auto-switch if a provider is down?',
            type: 'boolean',
            required: false,
            tier: 'detailed',
            description: 'Automatically tries another AI provider if the first one fails',
            default: true,
          },
        ],
      },
      {
        id: 'ml-model',
        name: 'ML Model Serving',
        description: 'Deploy and serve machine learning models with GPU support',
        icon: 'Brain',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          {
            provider: 'aws',
            resource_type: 'aws:sagemaker:Endpoint',
            display_name: 'SageMaker Endpoint',
          },
          {
            provider: 'gcp',
            resource_type: 'gcp:aiplatform:Endpoint',
            display_name: 'Vertex AI Endpoint',
          },
          {
            provider: 'azure',
            resource_type: 'azure:machinelearningservices:OnlineEndpoint',
            display_name: 'Azure ML Endpoint',
          },
        ],
        keywords: ['ml', 'model', 'sagemaker', 'vertex', 'inference', 'serving', 'gpu'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this model',
            placeholder: 'My ML Model',
          },
          {
            name: 'size',
            label: 'Instance type',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Hardware for model inference — GPU type determines speed and cost',
            default: 'ml.g5.xlarge',
            optionDetails: [
              {
                value: 'ml.t3.medium',
                label: 'ml.t3.medium (CPU)',
                description: '2 vCPU · 4 GB RAM · No GPU',
                cost: '~$50/mo',
                provider: 'aws',
              },
              {
                value: 'ml.g5.xlarge',
                label: 'ml.g5.xlarge',
                description: '4 vCPU · 16 GB · 1x A10G (24 GB)',
                cost: '~$816/mo',
                provider: 'aws',
              },
              {
                value: 'ml.g5.2xlarge',
                label: 'ml.g5.2xlarge',
                description: '8 vCPU · 32 GB · 1x A10G (24 GB)',
                cost: '~$1,190/mo',
                provider: 'aws',
              },
              {
                value: 'ml.p3.2xlarge',
                label: 'ml.p3.2xlarge',
                description: '8 vCPU · 61 GB · 1x V100 (16 GB)',
                cost: '~$2,300/mo',
                provider: 'aws',
              },
              {
                value: 'ml.p4d.24xlarge',
                label: 'ml.p4d.24xlarge',
                description: '96 vCPU · 1.1 TB · 8x A100 (40 GB)',
                cost: '~$23,600/mo',
                provider: 'aws',
              },
              {
                value: 'n1-standard-4-t4',
                label: 'n1-std-4 + T4',
                description: '4 vCPU · 15 GB · 1x T4 (16 GB)',
                cost: '~$350/mo',
                provider: 'gcp',
              },
              {
                value: 'n1-standard-8-l4',
                label: 'n1-std-8 + L4',
                description: '8 vCPU · 30 GB · 1x L4 (24 GB)',
                cost: '~$670/mo',
                provider: 'gcp',
              },
              {
                value: 'a2-highgpu-1g',
                label: 'a2-highgpu-1g',
                description: '12 vCPU · 85 GB · 1x A100 (40 GB)',
                cost: '~$2,500/mo',
                provider: 'gcp',
              },
              {
                value: 'Standard_NC4as_T4_v3',
                label: 'NC4as T4 v3',
                description: '4 vCPU · 28 GB · 1x T4 (16 GB)',
                cost: '~$380/mo',
                provider: 'azure',
              },
              {
                value: 'Standard_NC24ads_A100_v4',
                label: 'NC24ads A100 v4',
                description: '24 vCPU · 220 GB · 1x A100 (80 GB)',
                cost: '~$3,670/mo',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'framework',
            label: 'ML framework',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'What framework was your model built with?',
            default: 'pytorch',
            optionDetails: [
              { value: 'pytorch', label: 'PyTorch', description: 'Most popular — flexible and fast' },
              { value: 'tensorflow', label: 'TensorFlow', description: 'Production-grade — TF Serving' },
              { value: 'onnx', label: 'ONNX', description: 'Cross-framework portable format' },
              { value: 'vllm', label: 'vLLM', description: 'Optimized LLM serving' },
              { value: 'triton', label: 'Triton', description: 'NVIDIA multi-framework server' },
              { value: 'custom', label: 'Custom', description: 'Bring your own serving code' },
            ],
          },
        ],
      },
      {
        id: 'private-ai-service',
        name: 'Private AI Service',
        description: 'Self-hosted LLM running on your own GPU infrastructure — data stays in your cloud',
        icon: 'Brain',
        category: 'compute',
        behavior: 'scalable' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          { provider: 'aws', resource_type: 'aws:eks:NodeGroup', display_name: 'EKS GPU NodeGroup' },
          { provider: 'gcp', resource_type: 'gcp:container:NodePool', display_name: 'GKE GPU Node Pool' },
          { provider: 'azure', resource_type: 'azure:containerservice:AgentPool', display_name: 'AKS GPU Node Pool' },
        ],
        keywords: ['llm', 'self-hosted', 'private', 'llama', 'mistral', 'vllm', 'gpu', 'ai', 'ollama'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this AI service',
            placeholder: 'My Private AI',
          },
          {
            name: 'model',
            label: 'Model',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Open-weight model to serve',
            default: 'llama-3-8b',
            options: [
              'llama-3-8b',
              'llama-3-70b',
              'llama-3.1-8b',
              'llama-3.1-70b',
              'mistral-7b',
              'mixtral-8x7b',
              'qwen-2.5-7b',
              'qwen-2.5-72b',
              'phi-3-mini',
              'gemma-2-9b',
              'custom',
            ],
          },
          {
            name: 'runtime',
            label: 'Serving runtime',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'How the model is served',
            default: 'vllm',
            options: ['vllm', 'tgi', 'ollama', 'llama.cpp', 'triton'],
          },
          {
            name: 'gpu_type',
            label: 'GPU',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'GPU class — determines throughput and cost',
            default: 'nvidia-l4',
            optionDetails: [
              {
                value: 'nvidia-t4',
                label: 'NVIDIA T4 (16GB)',
                description: 'Entry-level — 7B models',
                cost: '~$350/mo',
              },
              {
                value: 'nvidia-l4',
                label: 'NVIDIA L4 (24GB)',
                description: 'Balanced — 7B-13B models',
                cost: '~$450/mo',
              },
              {
                value: 'nvidia-a10',
                label: 'NVIDIA A10 (24GB)',
                description: 'Mid-range — 13B models',
                cost: '~$700/mo',
              },
              {
                value: 'nvidia-a100-40',
                label: 'NVIDIA A100 40GB',
                description: 'High-end — 70B quantized',
                cost: '~$2200/mo',
              },
              {
                value: 'nvidia-a100-80',
                label: 'NVIDIA A100 80GB',
                description: 'High-end — 70B full-precision',
                cost: '~$3000/mo',
              },
              {
                value: 'nvidia-h100',
                label: 'NVIDIA H100 (80GB)',
                description: 'Top-tier — best throughput',
                cost: '~$5000/mo',
              },
            ],
          },
          {
            name: 'replicas',
            label: 'Replicas',
            type: 'number',
            required: false,
            tier: 'detailed',
            description: 'Number of GPU pods to run. Each replica serves requests in parallel.',
            default: 1,
          },
          {
            name: 'context_length',
            label: 'Context length',
            type: 'select',
            required: false,
            tier: 'detailed',
            description: 'Maximum tokens per request — longer contexts use more memory',
            default: '8k',
            options: ['2k', '4k', '8k', '16k', '32k', '128k'],
          },
        ],
      },
    ],
  };
