/**
 * High-level resource category: DATABASE.
 *
 * Relational, NoSQL, and cache databases.
 *
 * SIZE EXCEPTION: this file is intentionally >500 LOC because it is dominated
 * by data — the per-resource property catalogues, instance-size pickers, and
 * provider implementations together total ~2170 LOC of pure literal. Splitting
 * further would fragment the data without improving readability.
 *
 * The exported `database: HighLevelCategory` is consumed by `../high-level-resources.ts`
 * which assembles it into `HIGH_LEVEL_CATEGORIES`. The shape and content are
 * byte-identical to what was previously inlined there.
 */

// `NodeBehavior` is imported because the data literal uses `behavior: '...' as NodeBehavior` casts.
import type { HighLevelCategory, NodeBehavior } from '../types';
export type { NodeBehavior };

export const database: HighLevelCategory = {
  id: 'database',
  name: 'Database',
  description: 'Relational, NoSQL, and cache databases',
  icon: 'Database',
  resources: [
    {
      id: 'postgres-db',
      name: 'PostgreSQL',
      description: 'Managed PostgreSQL relational database',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure', 'digitalocean'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:rds:Instance', display_name: 'RDS PostgreSQL' },
        {
          provider: 'gcp',
          resource_type: 'gcp:sql:DatabaseInstance',
          display_name: 'Cloud SQL PostgreSQL',
        },
        {
          provider: 'azure',
          resource_type: 'azure:postgresql:Server',
          display_name: 'Azure PostgreSQL',
        },
        {
          provider: 'digitalocean',
          resource_type: 'digitalocean:database:Cluster',
          display_name: 'DO Managed PostgreSQL',
        },
      ],
      keywords: ['postgres', 'postgresql', 'rds', 'sql', 'database', 'cloudsql'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'size',
          label: 'Instance type',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Database server size — determines CPU, memory, and performance',
          default: 'db.t3.micro',
          tooltip:
            'AWS RDS: Burstable (t3) for dev/test, Memory-optimized (r6g) for production. GCP Cloud SQL: Custom machine types up to 96 vCPU / 624 GB. Azure: Burstable (B) for dev, General Purpose (D) for production.',
          optionDetails: [
            {
              value: 'db.t3.micro',
              label: 'db.t3.micro',
              description: '2 vCPU · 1 GB RAM',
              cost: '~$15/mo',
              provider: 'aws',
              tooltip: 'Burstable instance — good for dev/test with intermittent CPU needs',
            },
            {
              value: 'db.t3.small',
              label: 'db.t3.small',
              description: '2 vCPU · 2 GB RAM',
              cost: '~$29/mo',
              provider: 'aws',
            },
            {
              value: 'db.t3.medium',
              label: 'db.t3.medium',
              description: '2 vCPU · 4 GB RAM',
              cost: '~$58/mo',
              provider: 'aws',
            },
            {
              value: 'db.t3.large',
              label: 'db.t3.large',
              description: '2 vCPU · 8 GB RAM',
              cost: '~$116/mo',
              provider: 'aws',
              tooltip: 'Largest burstable instance — good for small production workloads',
            },
            {
              value: 'db.r6g.large',
              label: 'db.r6g.large',
              description: '2 vCPU · 16 GB RAM',
              cost: '~$175/mo',
              provider: 'aws',
              tooltip: 'Memory-optimized (Graviton2) — recommended for production databases',
            },
            {
              value: 'db.r6g.xlarge',
              label: 'db.r6g.xlarge',
              description: '4 vCPU · 32 GB RAM',
              cost: '~$350/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.2xlarge',
              label: 'db.r6g.2xlarge',
              description: '8 vCPU · 64 GB RAM',
              cost: '~$700/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.4xlarge',
              label: 'db.r6g.4xlarge',
              description: '16 vCPU · 128 GB RAM',
              cost: '~$1,400/mo',
              provider: 'aws',
            },
            {
              value: 'db-f1-micro',
              label: 'db-f1-micro',
              description: 'Shared vCPU · 0.6 GB RAM',
              cost: '~$10/mo',
              provider: 'gcp',
              tooltip: 'Shared-core instance — suitable for development and testing only',
            },
            {
              value: 'db-g1-small',
              label: 'db-g1-small',
              description: 'Shared vCPU · 1.7 GB RAM',
              cost: '~$25/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-2-8192',
              label: 'db-custom-2-8192',
              description: '2 vCPU · 8 GB RAM',
              cost: '~$97/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-4-16384',
              label: 'db-custom-4-16384',
              description: '4 vCPU · 16 GB RAM',
              cost: '~$190/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-8-32768',
              label: 'db-custom-8-32768',
              description: '8 vCPU · 32 GB RAM',
              cost: '~$380/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-16-65536',
              label: 'db-custom-16-65536',
              description: '16 vCPU · 64 GB RAM',
              cost: '~$760/mo',
              provider: 'gcp',
            },
            {
              value: 'B_Standard_B1ms',
              label: 'B1ms',
              description: '1 vCPU · 2 GB RAM',
              cost: '~$14/mo',
              provider: 'azure',
              tooltip: "Burstable tier — for workloads that don't use the CPU continuously",
            },
            {
              value: 'B_Standard_B2s',
              label: 'B2s',
              description: '2 vCPU · 4 GB RAM',
              cost: '~$50/mo',
              provider: 'azure',
            },
            {
              value: 'GP_Standard_D2s_v3',
              label: 'D2s v3',
              description: '2 vCPU · 8 GB RAM',
              cost: '~$100/mo',
              provider: 'azure',
              tooltip: 'General Purpose — balanced compute and memory for most production workloads',
            },
            {
              value: 'GP_Standard_D4s_v3',
              label: 'D4s v3',
              description: '4 vCPU · 16 GB RAM',
              cost: '~$200/mo',
              provider: 'azure',
            },
            {
              value: 'GP_Standard_D8s_v3',
              label: 'D8s v3',
              description: '8 vCPU · 32 GB RAM',
              cost: '~$400/mo',
              provider: 'azure',
            },
            {
              value: 'GP_Standard_D16s_v3',
              label: 'D16s v3',
              description: '16 vCPU · 64 GB RAM',
              cost: '~$800/mo',
              provider: 'azure',
            },
            {
              value: 'db-s-1vcpu-1gb',
              label: '1 vCPU / 1 GB',
              description: '1 vCPU · 1 GB RAM · 10 GB disk',
              cost: '~$15/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-1vcpu-2gb',
              label: '1 vCPU / 2 GB',
              description: '1 vCPU · 2 GB RAM · 25 GB disk',
              cost: '~$30/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-2vcpu-4gb',
              label: '2 vCPU / 4 GB',
              description: '2 vCPU · 4 GB RAM · 38 GB disk',
              cost: '~$60/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-4vcpu-8gb',
              label: '4 vCPU / 8 GB',
              description: '4 vCPU · 8 GB RAM · 115 GB disk',
              cost: '~$120/mo',
              provider: 'digitalocean',
            },
          ],
        },
        {
          name: 'storage',
          label: 'Storage',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Disk space for your data',
          default: '20',
          tooltip:
            'AWS RDS: 20 GB – 64 TB (gp3/io1). GCP Cloud SQL: 10 GB – 64 TB. Azure: 32 GB – 32 TB. Storage can be increased later without downtime on most providers.',
          optionDetails: [
            { value: '20', label: '20 GB', description: 'Development and small apps' },
            { value: '50', label: '50 GB', description: 'Small production workload' },
            { value: '100', label: '100 GB', description: 'Medium production workload' },
            { value: '250', label: '250 GB', description: 'Growing production workload' },
            { value: '500', label: '500 GB', description: 'Large datasets' },
            { value: '1000', label: '1 TB', description: 'Very large datasets' },
            { value: '2000', label: '2 TB', description: 'Enterprise workload' },
            { value: '5000', label: '5 TB', description: 'Large enterprise workload' },
            { value: '10000', label: '10 TB', description: 'Data-intensive workload' },
            { value: 'custom', label: 'Custom', description: 'Enter a specific storage size' },
          ],
          customInput: { type: 'number', unit: 'GB', min: 10, max: 65536, step: 10, placeholder: 'e.g. 750' },
        },
        {
          name: 'version',
          label: 'Version',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'PostgreSQL engine version',
          default: '17',
          tooltip:
            'Newer versions offer better performance, security patches, and features. Older versions are available for compatibility. Check your provider for exact version support.',
          optionDetails: [
            { value: '17', label: 'PostgreSQL 17', description: 'Latest — newest features and best performance' },
            { value: '16', label: 'PostgreSQL 16', description: 'Stable — widely supported (recommended)' },
            { value: '15', label: 'PostgreSQL 15', description: 'Mature — long-term support' },
            { value: '14', label: 'PostgreSQL 14', description: 'Older — long-term support until Nov 2026' },
            {
              value: '13',
              label: 'PostgreSQL 13',
              description: 'Legacy — end of life Nov 2025',
              tooltip: 'No longer receiving security updates. Upgrade recommended.',
            },
          ],
        },
        {
          name: 'production',
          label: 'Production-ready?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Enables automatic backups, multi-AZ high availability, and encryption at rest',
          default: false,
          tooltip:
            'AWS: Multi-AZ deployment with synchronous standby. GCP: Regional instance with automatic failover. Azure: Zone-redundant HA. Roughly doubles the cost but protects against outages.',
        },
        {
          name: 'backup_retention',
          label: 'Backup retention',
          type: 'select',
          required: false,
          tier: 'detailed',
          description: 'How many days to keep automated backups',
          default: '7',
          tooltip:
            'AWS RDS: 0–35 days. GCP Cloud SQL: 1–365 days. Azure: 7–35 days. Longer retention uses more storage and increases cost.',
          optionDetails: [
            // AWS RDS: 0–35 days
            { value: '1', label: '1 day', description: 'Minimum — dev only', provider: 'aws' },
            { value: '7', label: '7 days', description: 'Standard (recommended)', provider: 'aws' },
            { value: '14', label: '14 days', description: 'Extended retention', provider: 'aws' },
            { value: '30', label: '30 days', description: 'Monthly compliance window', provider: 'aws' },
            { value: '35', label: '35 days', description: 'Maximum', provider: 'aws' },
            { value: 'custom', label: 'Custom', description: 'Enter retention (0–35 days)', provider: 'aws' },
            // GCP Cloud SQL: 1–365 days
            { value: '1', label: '1 day', description: 'Minimum — dev only', provider: 'gcp' },
            { value: '7', label: '7 days', description: 'Standard (recommended)', provider: 'gcp' },
            { value: '14', label: '14 days', description: 'Extended retention', provider: 'gcp' },
            { value: '30', label: '30 days', description: 'Monthly compliance window', provider: 'gcp' },
            { value: '90', label: '90 days', description: 'Quarterly compliance', provider: 'gcp' },
            { value: '365', label: '365 days', description: 'Maximum', provider: 'gcp' },
            { value: 'custom', label: 'Custom', description: 'Enter retention (1–365 days)', provider: 'gcp' },
            // Azure: 7–35 days
            { value: '7', label: '7 days', description: 'Minimum (recommended)', provider: 'azure' },
            { value: '14', label: '14 days', description: 'Extended retention', provider: 'azure' },
            { value: '30', label: '30 days', description: 'Monthly compliance window', provider: 'azure' },
            { value: '35', label: '35 days', description: 'Maximum', provider: 'azure' },
            { value: 'custom', label: 'Custom', description: 'Enter retention (7–35 days)', provider: 'azure' },
            // DigitalOcean: automatic backups (7 days included)
            { value: '7', label: '7 days', description: 'Included with backups', provider: 'digitalocean' },
          ],
          customInput: { type: 'number', unit: 'days', min: 1, max: 365, step: 1, placeholder: 'e.g. 21' },
        },
      ],
    },
    {
      id: 'mysql-db',
      name: 'MySQL',
      description: 'Managed MySQL relational database',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure', 'digitalocean'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:rds:Instance', display_name: 'RDS MySQL' },
        {
          provider: 'gcp',
          resource_type: 'gcp:sql:DatabaseInstance',
          display_name: 'Cloud SQL MySQL',
        },
        { provider: 'azure', resource_type: 'azure:mysql:Server', display_name: 'Azure MySQL' },
        {
          provider: 'digitalocean',
          resource_type: 'digitalocean:database:Cluster',
          display_name: 'DO Managed MySQL',
        },
      ],
      keywords: ['mysql', 'rds', 'sql', 'database', 'aurora', 'mariadb'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'size',
          label: 'Instance type',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Database server size — determines CPU, memory, and performance',
          default: 'db.t3.micro',
          tooltip:
            'AWS RDS: Burstable (t3) for dev/test, Memory-optimized (r6g) for production. GCP Cloud SQL: Custom machine types up to 96 vCPU / 624 GB. Azure: Burstable (B) for dev, General Purpose (D) for production.',
          optionDetails: [
            {
              value: 'db.t3.micro',
              label: 'db.t3.micro',
              description: '2 vCPU · 1 GB RAM',
              cost: '~$15/mo',
              provider: 'aws',
            },
            {
              value: 'db.t3.small',
              label: 'db.t3.small',
              description: '2 vCPU · 2 GB RAM',
              cost: '~$29/mo',
              provider: 'aws',
            },
            {
              value: 'db.t3.medium',
              label: 'db.t3.medium',
              description: '2 vCPU · 4 GB RAM',
              cost: '~$58/mo',
              provider: 'aws',
            },
            {
              value: 'db.t3.large',
              label: 'db.t3.large',
              description: '2 vCPU · 8 GB RAM',
              cost: '~$116/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.large',
              label: 'db.r6g.large',
              description: '2 vCPU · 16 GB RAM',
              cost: '~$175/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.xlarge',
              label: 'db.r6g.xlarge',
              description: '4 vCPU · 32 GB RAM',
              cost: '~$350/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.2xlarge',
              label: 'db.r6g.2xlarge',
              description: '8 vCPU · 64 GB RAM',
              cost: '~$700/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.4xlarge',
              label: 'db.r6g.4xlarge',
              description: '16 vCPU · 128 GB RAM',
              cost: '~$1,400/mo',
              provider: 'aws',
            },
            {
              value: 'db-f1-micro',
              label: 'db-f1-micro',
              description: 'Shared vCPU · 0.6 GB RAM',
              cost: '~$10/mo',
              provider: 'gcp',
            },
            {
              value: 'db-g1-small',
              label: 'db-g1-small',
              description: 'Shared vCPU · 1.7 GB RAM',
              cost: '~$25/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-2-8192',
              label: 'db-custom-2-8192',
              description: '2 vCPU · 8 GB RAM',
              cost: '~$97/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-4-16384',
              label: 'db-custom-4-16384',
              description: '4 vCPU · 16 GB RAM',
              cost: '~$190/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-8-32768',
              label: 'db-custom-8-32768',
              description: '8 vCPU · 32 GB RAM',
              cost: '~$380/mo',
              provider: 'gcp',
            },
            {
              value: 'db-custom-16-65536',
              label: 'db-custom-16-65536',
              description: '16 vCPU · 64 GB RAM',
              cost: '~$760/mo',
              provider: 'gcp',
            },
            {
              value: 'B_Standard_B1ms',
              label: 'B1ms',
              description: '1 vCPU · 2 GB RAM',
              cost: '~$14/mo',
              provider: 'azure',
            },
            {
              value: 'B_Standard_B2s',
              label: 'B2s',
              description: '2 vCPU · 4 GB RAM',
              cost: '~$50/mo',
              provider: 'azure',
            },
            {
              value: 'GP_Standard_D2s_v3',
              label: 'D2s v3',
              description: '2 vCPU · 8 GB RAM',
              cost: '~$100/mo',
              provider: 'azure',
            },
            {
              value: 'GP_Standard_D4s_v3',
              label: 'D4s v3',
              description: '4 vCPU · 16 GB RAM',
              cost: '~$200/mo',
              provider: 'azure',
            },
            {
              value: 'GP_Standard_D8s_v3',
              label: 'D8s v3',
              description: '8 vCPU · 32 GB RAM',
              cost: '~$400/mo',
              provider: 'azure',
            },
            {
              value: 'GP_Standard_D16s_v3',
              label: 'D16s v3',
              description: '16 vCPU · 64 GB RAM',
              cost: '~$800/mo',
              provider: 'azure',
            },
            {
              value: 'db-s-1vcpu-1gb',
              label: '1 vCPU / 1 GB',
              description: '1 vCPU · 1 GB RAM · 10 GB disk',
              cost: '~$15/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-1vcpu-2gb',
              label: '1 vCPU / 2 GB',
              description: '1 vCPU · 2 GB RAM · 25 GB disk',
              cost: '~$30/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-2vcpu-4gb',
              label: '2 vCPU / 4 GB',
              description: '2 vCPU · 4 GB RAM · 38 GB disk',
              cost: '~$60/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-4vcpu-8gb',
              label: '4 vCPU / 8 GB',
              description: '4 vCPU · 8 GB RAM · 115 GB disk',
              cost: '~$120/mo',
              provider: 'digitalocean',
            },
          ],
        },
        {
          name: 'storage',
          label: 'Storage',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Disk space for your data',
          default: '20',
          tooltip:
            'AWS RDS: 20 GB – 64 TB (gp3/io1). GCP Cloud SQL: 10 GB – 64 TB. Azure: 32 GB – 32 TB. Storage can be increased later without downtime on most providers.',
          optionDetails: [
            { value: '20', label: '20 GB', description: 'Development and small apps' },
            { value: '50', label: '50 GB', description: 'Small production workload' },
            { value: '100', label: '100 GB', description: 'Medium production workload' },
            { value: '250', label: '250 GB', description: 'Growing production workload' },
            { value: '500', label: '500 GB', description: 'Large datasets' },
            { value: '1000', label: '1 TB', description: 'Very large datasets' },
            { value: '2000', label: '2 TB', description: 'Enterprise workload' },
            { value: '5000', label: '5 TB', description: 'Large enterprise workload' },
            { value: '10000', label: '10 TB', description: 'Data-intensive workload' },
            { value: 'custom', label: 'Custom', description: 'Enter a specific storage size' },
          ],
          customInput: { type: 'number', unit: 'GB', min: 10, max: 65536, step: 10, placeholder: 'e.g. 750' },
        },
        {
          name: 'version',
          label: 'Version',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'MySQL engine version',
          default: '8.4',
          tooltip:
            'MySQL 8.4 is the current LTS release. MySQL 8.0 remains widely supported. MySQL 5.7 reached end of life Oct 2023 — no security patches.',
          optionDetails: [
            { value: '8.4', label: 'MySQL 8.4 LTS', description: 'Latest LTS — recommended for new projects' },
            { value: '8.0', label: 'MySQL 8.0', description: 'Previous LTS — widely deployed' },
            {
              value: '5.7',
              label: 'MySQL 5.7',
              description: 'End of life Oct 2023 — upgrade recommended',
              tooltip: 'No longer receiving security updates. Migrate to 8.x as soon as possible.',
            },
          ],
        },
        {
          name: 'production',
          label: 'Production-ready?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Enables automatic backups, multi-AZ high availability, and encryption at rest',
          default: false,
          tooltip: 'Roughly doubles the cost but protects against outages with automatic failover.',
        },
        {
          name: 'backup_retention',
          label: 'Backup retention',
          type: 'select',
          required: false,
          tier: 'detailed',
          description: 'How many days to keep automated backups',
          default: '7',
          tooltip: 'AWS RDS: 0–35 days. GCP Cloud SQL: 1–365 days. Azure: 7–35 days.',
          optionDetails: [
            // AWS RDS: 0–35 days
            { value: '1', label: '1 day', description: 'Minimum — dev only', provider: 'aws' },
            { value: '7', label: '7 days', description: 'Standard (recommended)', provider: 'aws' },
            { value: '14', label: '14 days', description: 'Extended retention', provider: 'aws' },
            { value: '30', label: '30 days', description: 'Monthly compliance window', provider: 'aws' },
            { value: '35', label: '35 days', description: 'Maximum', provider: 'aws' },
            { value: 'custom', label: 'Custom', description: 'Enter retention (0–35 days)', provider: 'aws' },
            // GCP Cloud SQL: 1–365 days
            { value: '1', label: '1 day', description: 'Minimum — dev only', provider: 'gcp' },
            { value: '7', label: '7 days', description: 'Standard (recommended)', provider: 'gcp' },
            { value: '14', label: '14 days', description: 'Extended retention', provider: 'gcp' },
            { value: '30', label: '30 days', description: 'Monthly compliance window', provider: 'gcp' },
            { value: '90', label: '90 days', description: 'Quarterly compliance', provider: 'gcp' },
            { value: '365', label: '365 days', description: 'Maximum', provider: 'gcp' },
            { value: 'custom', label: 'Custom', description: 'Enter retention (1–365 days)', provider: 'gcp' },
            // Azure: 7–35 days
            { value: '7', label: '7 days', description: 'Minimum (recommended)', provider: 'azure' },
            { value: '14', label: '14 days', description: 'Extended retention', provider: 'azure' },
            { value: '30', label: '30 days', description: 'Monthly compliance window', provider: 'azure' },
            { value: '35', label: '35 days', description: 'Maximum', provider: 'azure' },
            { value: 'custom', label: 'Custom', description: 'Enter retention (7–35 days)', provider: 'azure' },
            // DigitalOcean: automatic backups (7 days included)
            { value: '7', label: '7 days', description: 'Included with backups', provider: 'digitalocean' },
          ],
          customInput: { type: 'number', unit: 'days', min: 1, max: 365, step: 1, placeholder: 'e.g. 21' },
        },
      ],
    },
    {
      id: 'mongodb',
      name: 'MongoDB',
      description: 'Managed NoSQL document database',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws', 'azure', 'digitalocean'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:docdb:Cluster', display_name: 'DocumentDB' },
        { provider: 'azure', resource_type: 'azure:cosmosdb:Account', display_name: 'Cosmos DB' },
        {
          provider: 'digitalocean',
          resource_type: 'digitalocean:database:Cluster',
          display_name: 'DO Managed MongoDB',
        },
      ],
      keywords: ['mongo', 'mongodb', 'nosql', 'documentdb', 'cosmos'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'size',
          label: 'Instance type',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Database server size — determines CPU, memory, and performance',
          default: 'db.t3.medium',
          tooltip:
            'AWS DocumentDB: r6g instances recommended for production. Azure Cosmos DB: measured in Request Units/s — 1 RU ≈ one 1 KB document read. DigitalOcean: fixed-size nodes.',
          optionDetails: [
            {
              value: 'db.t3.medium',
              label: 'db.t3.medium',
              description: '2 vCPU · 4 GB RAM',
              cost: '~$58/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.large',
              label: 'db.r6g.large',
              description: '2 vCPU · 16 GB RAM',
              cost: '~$175/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.xlarge',
              label: 'db.r6g.xlarge',
              description: '4 vCPU · 32 GB RAM',
              cost: '~$350/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.2xlarge',
              label: 'db.r6g.2xlarge',
              description: '8 vCPU · 64 GB RAM',
              cost: '~$700/mo',
              provider: 'aws',
            },
            {
              value: 'db.r6g.4xlarge',
              label: 'db.r6g.4xlarge',
              description: '16 vCPU · 128 GB RAM',
              cost: '~$1,400/mo',
              provider: 'aws',
            },
            {
              value: 'cosmos-serverless',
              label: 'Serverless',
              description: 'MongoDB API · pay-per-request',
              cost: '~$0.25/M RUs',
              provider: 'azure',
              tooltip: 'Best for intermittent or unpredictable traffic — scales to zero',
            },
            {
              value: 'cosmos-400',
              label: '400 RU/s',
              description: 'MongoDB API · light workloads',
              cost: '~$24/mo',
              provider: 'azure',
            },
            {
              value: 'cosmos-1000',
              label: '1,000 RU/s',
              description: 'MongoDB API · standard',
              cost: '~$58/mo',
              provider: 'azure',
            },
            {
              value: 'cosmos-4000',
              label: '4,000 RU/s',
              description: 'MongoDB API · heavy workloads',
              cost: '~$233/mo',
              provider: 'azure',
            },
            {
              value: 'cosmos-autoscale',
              label: 'Autoscale (4,000 max)',
              description: 'MongoDB API · auto-scaling 400–4,000 RU/s',
              cost: '~$175/mo max',
              provider: 'azure',
            },
            {
              value: 'cosmos-autoscale-10k',
              label: 'Autoscale (10,000 max)',
              description: 'MongoDB API · auto-scaling 1,000–10,000 RU/s',
              cost: '~$438/mo max',
              provider: 'azure',
            },
            {
              value: 'db-s-1vcpu-1gb',
              label: '1 vCPU / 1 GB',
              description: '1 vCPU · 1 GB RAM · 10 GB disk',
              cost: '~$15/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-1vcpu-2gb',
              label: '1 vCPU / 2 GB',
              description: '1 vCPU · 2 GB RAM · 20 GB disk',
              cost: '~$30/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-2vcpu-4gb',
              label: '2 vCPU / 4 GB',
              description: '2 vCPU · 4 GB RAM · 38 GB disk',
              cost: '~$60/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-4vcpu-8gb',
              label: '4 vCPU / 8 GB',
              description: '4 vCPU · 8 GB RAM · 115 GB disk',
              cost: '~$120/mo',
              provider: 'digitalocean',
            },
          ],
        },
        {
          name: 'storage',
          label: 'Storage',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Disk space for your data',
          default: '20',
          tooltip:
            'AWS DocumentDB: storage auto-scales in 10 GB increments up to 128 TB. Azure Cosmos DB: storage is included with throughput. DigitalOcean: included with instance size.',
          optionDetails: [
            { value: '20', label: '20 GB', description: 'Development and small apps' },
            { value: '50', label: '50 GB', description: 'Small production workload' },
            { value: '100', label: '100 GB', description: 'Medium production workload' },
            { value: '250', label: '250 GB', description: 'Growing production workload' },
            { value: '500', label: '500 GB', description: 'Large datasets' },
            { value: '1000', label: '1 TB', description: 'Very large datasets' },
            { value: 'custom', label: 'Custom', description: 'Enter a specific storage size' },
          ],
          customInput: { type: 'number', unit: 'GB', min: 10, max: 131072, step: 10, placeholder: 'e.g. 300' },
        },
        {
          name: 'version',
          label: 'Version',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'MongoDB compatibility version',
          default: '7.0',
          tooltip:
            'AWS DocumentDB supports MongoDB 4.0, 5.0, and 7.0 compatible APIs. Azure Cosmos DB supports MongoDB 4.2, 5.0, 6.0, 7.0 APIs.',
          optionDetails: [
            {
              value: '8.0',
              label: 'MongoDB 8.0',
              description: 'Latest — newest features',
              tooltip: 'Not yet supported on all managed providers — check availability',
            },
            { value: '7.0', label: 'MongoDB 7.0', description: 'Stable — best performance (recommended)' },
            { value: '6.0', label: 'MongoDB 6.0', description: 'Previous stable — widely supported' },
            { value: '5.0', label: 'MongoDB 5.0', description: 'Mature — long-term support' },
          ],
        },
        {
          name: 'production',
          label: 'Production-ready?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Turns on automatic backups, high availability, and encryption',
          default: false,
          tooltip:
            'AWS DocumentDB: multi-AZ with read replicas. Azure Cosmos DB: multi-region writes. DigitalOcean: standby node with automatic failover.',
        },
      ],
    },
    {
      id: 'redis-cache',
      name: 'Redis Cache',
      description: 'In-memory cache for fast data access',
      icon: 'Zap',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure', 'digitalocean'],
      implementations: [
        {
          provider: 'aws',
          resource_type: 'aws:elasticache:Cluster',
          display_name: 'ElastiCache Redis',
        },
        {
          provider: 'gcp',
          resource_type: 'gcp:redis:Instance',
          display_name: 'Memorystore Redis',
        },
        {
          provider: 'azure',
          resource_type: 'azure:redis:Cache',
          display_name: 'Azure Cache for Redis',
        },
        {
          provider: 'digitalocean',
          resource_type: 'digitalocean:database:Cluster',
          display_name: 'DO Managed Redis',
        },
      ],
      keywords: ['redis', 'cache', 'elasticache', 'memorystore', 'memory'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this cache',
          placeholder: 'My Cache',
        },
        {
          name: 'size',
          label: 'Node type',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Cache node size — determines memory and performance',
          default: 'cache.t3.micro',
          tooltip:
            'AWS ElastiCache: burstable (t3) for dev, memory-optimized (r6g) for production. GCP Memorystore: basic (M1-M5) with no HA, or standard with replica. Azure Cache: shared (C0) for dev, dedicated (C1+) for production.',
          optionDetails: [
            {
              value: 'cache.t3.micro',
              label: 'cache.t3.micro',
              description: '0.5 GB RAM',
              cost: '~$12/mo',
              provider: 'aws',
              tooltip: 'Burstable — good for dev/test with intermittent usage',
            },
            {
              value: 'cache.t3.small',
              label: 'cache.t3.small',
              description: '1.4 GB RAM',
              cost: '~$24/mo',
              provider: 'aws',
            },
            {
              value: 'cache.t3.medium',
              label: 'cache.t3.medium',
              description: '3.09 GB RAM',
              cost: '~$48/mo',
              provider: 'aws',
            },
            {
              value: 'cache.r6g.large',
              label: 'cache.r6g.large',
              description: '13.07 GB RAM',
              cost: '~$135/mo',
              provider: 'aws',
              tooltip: 'Memory-optimized — recommended for production caching',
            },
            {
              value: 'cache.r6g.xlarge',
              label: 'cache.r6g.xlarge',
              description: '26.32 GB RAM',
              cost: '~$270/mo',
              provider: 'aws',
            },
            {
              value: 'cache.r6g.2xlarge',
              label: 'cache.r6g.2xlarge',
              description: '52.82 GB RAM',
              cost: '~$540/mo',
              provider: 'aws',
            },
            {
              value: 'M1',
              label: 'M1 (1 GB)',
              description: '1 GB RAM · Basic tier',
              cost: '~$35/mo',
              provider: 'gcp',
            },
            {
              value: 'M2',
              label: 'M2 (4 GB)',
              description: '4 GB RAM · Basic tier',
              cost: '~$110/mo',
              provider: 'gcp',
            },
            {
              value: 'M3',
              label: 'M3 (10 GB)',
              description: '10 GB RAM · Basic tier',
              cost: '~$280/mo',
              provider: 'gcp',
            },
            {
              value: 'M4',
              label: 'M4 (35 GB)',
              description: '35 GB RAM · Basic tier',
              cost: '~$950/mo',
              provider: 'gcp',
            },
            {
              value: 'C0',
              label: 'C0',
              description: '250 MB · Shared',
              cost: '~$16/mo',
              provider: 'azure',
              tooltip: 'Shared infrastructure — not recommended for production',
            },
            { value: 'C1', label: 'C1', description: '1 GB · Dedicated', cost: '~$41/mo', provider: 'azure' },
            { value: 'C2', label: 'C2', description: '2.5 GB · Dedicated', cost: '~$68/mo', provider: 'azure' },
            { value: 'C3', label: 'C3', description: '6 GB · Dedicated', cost: '~$135/mo', provider: 'azure' },
            {
              value: 'P1',
              label: 'P1 (Premium)',
              description: '6 GB · Clustering + persistence',
              cost: '~$218/mo',
              provider: 'azure',
              tooltip: 'Premium tier enables clustering, geo-replication, and data persistence',
            },
            {
              value: 'db-s-1vcpu-1gb',
              label: '1 vCPU / 1 GB',
              description: '1 vCPU · 1 GB RAM',
              cost: '~$15/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-1vcpu-2gb',
              label: '1 vCPU / 2 GB',
              description: '1 vCPU · 2 GB RAM',
              cost: '~$30/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-2vcpu-4gb',
              label: '2 vCPU / 4 GB',
              description: '2 vCPU · 4 GB RAM',
              cost: '~$60/mo',
              provider: 'digitalocean',
            },
          ],
        },
        {
          name: 'max_memory_policy',
          label: 'When memory is full?',
          type: 'select',
          required: false,
          tier: 'detailed',
          description: 'What Redis does when it runs out of memory',
          default: 'allkeys-lru',
          tooltip:
            'Controls eviction behavior. LRU (Least Recently Used) is best for caching. noeviction returns errors when full — use for persistent data.',
          optionDetails: [
            { value: 'allkeys-lru', label: 'Evict least recently used', description: 'Best for caching (default)' },
            {
              value: 'volatile-lru',
              label: 'Evict LRU with TTL only',
              description: 'Only evict keys with an expiration set',
            },
            {
              value: 'allkeys-random',
              label: 'Evict random keys',
              description: 'Random eviction — simple but unpredictable',
            },
            {
              value: 'noeviction',
              label: 'Return errors when full',
              description: 'Never evict — use for persistent data',
            },
          ],
        },
        {
          name: 'keep_data_safe',
          label: 'Keep data safe if server restarts?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Saves cached data to disk so it survives restarts (slightly slower)',
          default: false,
          tooltip:
            'AWS: append-only file (AOF) or RDB snapshots. GCP: Standard tier includes replica. Azure: Premium tier only. Adds latency to writes.',
        },
        {
          name: 'version',
          label: 'Version',
          type: 'select',
          required: false,
          tier: 'detailed',
          description: 'Redis engine version',
          default: '7.x',
          tooltip: 'Redis 7.x adds Redis Functions, ACLv2, and sharded pub/sub. Redis 6.x is in maintenance mode.',
          optionDetails: [
            { value: '7.x', label: 'Redis 7.x', description: 'Latest — best performance (recommended)' },
            { value: '6.x', label: 'Redis 6.x', description: 'Previous stable — maintenance mode' },
          ],
        },
      ],
    },
    {
      id: 'dynamodb',
      name: 'DynamoDB',
      description: 'NoSQL key-value and document database with single-digit millisecond performance',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws'],
      implementations: [{ provider: 'aws', resource_type: 'aws:dynamodb:Table', display_name: 'DynamoDB Table' }],
      keywords: ['dynamodb', 'dynamo', 'nosql', 'key-value', 'document'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Table',
        },
        {
          name: 'capacity_mode',
          label: 'Capacity mode',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'How DynamoDB scales and bills for read/write throughput',
          default: 'on-demand',
          tooltip:
            'On-demand: no capacity planning, pay per request, auto-scales instantly. Provisioned: you specify read/write capacity units — up to 77% cheaper for predictable workloads. You can switch modes once every 24 hours.',
          optionDetails: [
            {
              value: 'on-demand',
              label: 'On-demand',
              description: 'Pay per request · auto-scales instantly',
              cost: '~$1.25/M writes',
              provider: 'aws',
              tooltip: 'Best for unpredictable traffic. No capacity planning needed.',
            },
            {
              value: 'provisioned',
              label: 'Provisioned',
              description: 'Reserved capacity · lower cost for steady traffic',
              cost: 'from $0.00065/WCU/hr',
              provider: 'aws',
              tooltip: 'Set read/write capacity units. Enable auto-scaling for variable loads at lower cost.',
            },
            {
              value: 'provisioned-autoscale',
              label: 'Provisioned + Auto-scaling',
              description: 'Reserved baseline · auto-scales within limits',
              cost: 'from $0.00065/WCU/hr',
              provider: 'aws',
              tooltip:
                'Combines cost savings of provisioned with flexibility. Set min/max capacity and target utilization.',
            },
          ],
        },
        {
          name: 'table_class',
          label: 'Table class',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Table storage class — affects storage cost vs read/write cost',
          default: 'standard',
          tooltip:
            'Standard: lower read/write cost, higher storage cost. Standard-IA: 60% lower storage cost, higher read/write cost — best when storage dominates.',
          optionDetails: [
            {
              value: 'standard',
              label: 'Standard',
              description: 'Default — lower read/write cost',
              cost: '~$0.25/GB/mo storage',
              provider: 'aws',
            },
            {
              value: 'standard-ia',
              label: 'Standard-IA',
              description: 'Infrequent access — 60% lower storage cost',
              cost: '~$0.10/GB/mo storage',
              provider: 'aws',
              tooltip: 'Best for tables where storage cost exceeds 50% of total cost. Higher per-request prices.',
            },
          ],
        },
        {
          name: 'lookup_field',
          label: 'Main lookup field',
          type: 'string',
          required: false,
          tier: 'detailed',
          description: 'The main field you will use to look up records (partition key)',
          placeholder: 'e.g. userId',
          tooltip:
            'This becomes the DynamoDB partition key. Choose a field with high cardinality (many unique values) for best performance.',
        },
        {
          name: 'sort_field',
          label: 'Sort field',
          type: 'string',
          required: false,
          tier: 'detailed',
          description: 'Optional second key for range queries within a partition',
          placeholder: 'e.g. timestamp',
          tooltip:
            'The sort key enables range queries like "all orders for user X between dates". Leave empty for simple key-value lookups.',
        },
        {
          name: 'enable_streams',
          label: 'Enable change streams?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Capture a time-ordered sequence of item-level changes',
          default: false,
          tooltip:
            'DynamoDB Streams captures inserts, updates, and deletes. Use to trigger Lambda functions, replicate data, or build event-driven architectures.',
        },
        {
          name: 'encryption',
          label: 'Encryption',
          type: 'select',
          required: false,
          tier: 'detailed',
          description: 'How data is encrypted at rest',
          default: 'aws-owned',
          tooltip: 'All DynamoDB data is encrypted at rest. Choose who manages the encryption key.',
          optionDetails: [
            {
              value: 'aws-owned',
              label: 'AWS owned key',
              description: 'Default — no extra cost',
              cost: 'Free',
              provider: 'aws',
            },
            {
              value: 'aws-managed',
              label: 'AWS managed key (KMS)',
              description: 'AWS manages the key in KMS',
              cost: '~$1/mo per key',
              provider: 'aws',
            },
            {
              value: 'customer-managed',
              label: 'Customer managed key',
              description: 'You manage the key in KMS',
              cost: '~$1/mo + API calls',
              provider: 'aws',
              tooltip: 'Full control over key rotation, deletion, and access policies',
            },
          ],
        },
      ],
    },
    {
      id: 'firestore',
      name: 'Firestore',
      description: 'Document database with real-time sync and offline support',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['gcp'],
      implementations: [
        {
          provider: 'gcp',
          resource_type: 'gcp:firestore:Database',
          display_name: 'Firestore Database',
        },
      ],
      keywords: ['firestore', 'firebase', 'document', 'realtime', 'nosql'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'size',
          label: 'Pricing plan',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Firebase pricing plan — determines quotas and billing',
          default: 'spark',
          optionDetails: [
            {
              value: 'spark',
              label: 'Spark (Free)',
              description: '1 GB storage · 50K reads/day · 20K writes/day',
              cost: 'Free',
              provider: 'gcp',
            },
            {
              value: 'blaze',
              label: 'Blaze (Pay-as-you-go)',
              description: 'Unlimited · pay per operation',
              cost: '~$0.06/100K reads',
              provider: 'gcp',
            },
          ],
        },
        {
          name: 'mode',
          label: 'Database mode',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Firestore operating mode',
          default: 'native',
          optionDetails: [
            {
              value: 'native',
              label: 'Native mode',
              description: 'Real-time sync, offline support, mobile SDKs',
              provider: 'gcp',
            },
            {
              value: 'datastore',
              label: 'Datastore mode',
              description: 'Server-side only, higher throughput',
              provider: 'gcp',
            },
          ],
        },
        {
          name: 'realtime',
          label: 'Live updates?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Push changes instantly to connected apps (great for chat, dashboards)',
          default: true,
        },
      ],
    },
    {
      id: 'cosmosdb',
      name: 'Cosmos DB',
      description: 'Multi-model database with global distribution and guaranteed low latency',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['azure'],
      implementations: [
        {
          provider: 'azure',
          resource_type: 'azure:cosmosdb:Account',
          display_name: 'Cosmos DB Account',
        },
      ],
      keywords: ['cosmosdb', 'cosmos', 'multi-model', 'global', 'nosql'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'size',
          label: 'Throughput',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Request Units per second — determines read/write capacity',
          default: 'serverless',
          tooltip:
            '1 RU = one 1 KB point read. A typical 4 KB document read costs ~4 RUs. Writes cost ~5x more than reads. Serverless is best for intermittent workloads. Provisioned autoscale is best for variable but continuous traffic.',
          optionDetails: [
            {
              value: 'serverless',
              label: 'Serverless',
              description: 'Pay per request · scales to zero',
              cost: '~$0.25/M RUs',
              provider: 'azure',
              tooltip:
                'Max 5,000 RU/s burst. Best for dev/test and intermittent workloads. Cannot enable geo-replication.',
            },
            {
              value: '400',
              label: '400 RU/s',
              description: 'Provisioned minimum · light workloads',
              cost: '~$24/mo',
              provider: 'azure',
            },
            {
              value: '1000',
              label: '1,000 RU/s',
              description: 'Standard workloads',
              cost: '~$58/mo',
              provider: 'azure',
            },
            {
              value: '4000',
              label: '4,000 RU/s',
              description: 'Heavy workloads',
              cost: '~$233/mo',
              provider: 'azure',
            },
            {
              value: '10000',
              label: '10,000 RU/s',
              description: 'Very heavy workloads',
              cost: '~$583/mo',
              provider: 'azure',
            },
            {
              value: 'autoscale-4000',
              label: 'Autoscale (4,000 max)',
              description: 'Auto-scales 400–4,000 RU/s',
              cost: '~$175/mo max',
              provider: 'azure',
              tooltip: 'Scales between 10% and 100% of max. You pay for the highest RU/s reached each hour.',
            },
            {
              value: 'autoscale-10000',
              label: 'Autoscale (10,000 max)',
              description: 'Auto-scales 1,000–10,000 RU/s',
              cost: '~$438/mo max',
              provider: 'azure',
            },
            {
              value: 'autoscale-40000',
              label: 'Autoscale (40,000 max)',
              description: 'Auto-scales 4,000–40,000 RU/s',
              cost: '~$1,750/mo max',
              provider: 'azure',
            },
            { value: 'custom', label: 'Custom RU/s', description: 'Enter specific throughput', provider: 'azure' },
          ],
          customInput: { type: 'number', unit: 'RU/s', min: 400, max: 1000000, step: 100, placeholder: 'e.g. 2500' },
        },
        {
          name: 'global',
          label: 'Available worldwide?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Copies your data to regions around the world for fast access everywhere',
          default: false,
          tooltip:
            'Each additional region roughly doubles the throughput cost. Not available with Serverless mode. Enables multi-region writes for highest availability.',
        },
        {
          name: 'data_safety',
          label: 'How important is data accuracy?',
          type: 'select',
          required: false,
          tier: 'detailed',
          description: 'Trade off between speed and data accuracy across regions',
          default: 'session',
          tooltip:
            'Consistency levels in order from fastest to most accurate: Eventual → Consistent Prefix → Session → Bounded Staleness → Strong. Stronger consistency uses more RUs per operation.',
          optionDetails: [
            {
              value: 'eventual',
              label: 'Eventual',
              description: 'Maximum speed — data may be briefly stale',
              provider: 'azure',
              tooltip:
                'Lowest latency and cost. Reads may return out-of-order. Use for counters, likes, non-critical data.',
            },
            {
              value: 'session',
              label: 'Session',
              description: 'Balanced — consistent within a session (recommended)',
              provider: 'azure',
              tooltip:
                'Default. A user always sees their own writes. Other users see eventual consistency. Best for most applications.',
            },
            {
              value: 'strong',
              label: 'Strong',
              description: 'Maximum accuracy — slightly slower',
              provider: 'azure',
              tooltip:
                'Linearizable reads. Highest RU cost (2x reads). Only available in single-region or with specific multi-region config.',
            },
            {
              value: 'bounded-staleness',
              label: 'Bounded staleness',
              description: 'Reads lag behind writes by a set window',
              provider: 'azure',
              tooltip:
                'Configurable staleness window (e.g., 5 seconds or 100 operations behind). Good compromise for multi-region.',
            },
            {
              value: 'consistent-prefix',
              label: 'Consistent prefix',
              description: 'Reads never see out-of-order writes',
              provider: 'azure',
              tooltip: 'Guarantees ordering but may be stale. Lower cost than bounded staleness.',
            },
          ],
        },
      ],
    },
    {
      id: 'tablestore',
      name: 'Tablestore',
      description: 'NoSQL wide-column store with serverless auto-scaling',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['alibaba'],
      implementations: [
        {
          provider: 'alibaba',
          resource_type: 'alibaba:ots:Instance',
          display_name: 'Tablestore Instance',
        },
      ],
      keywords: ['tablestore', 'ots', 'wide-column', 'nosql', 'alibaba'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'size',
          label: 'Capacity mode',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Billing and throughput model',
          default: 'on-demand',
          tooltip:
            'On-demand: best for unpredictable traffic, pay per Capacity Unit consumed. Reserved: pre-purchase CUs for steady workloads at lower per-unit cost. 1 read CU = one 4 KB read, 1 write CU = one 4 KB write.',
          optionDetails: [
            {
              value: 'on-demand',
              label: 'On-demand (CU)',
              description: 'Pay per Capacity Unit · auto-scales',
              cost: '~$0.007/10K CU',
              provider: 'alibaba',
              tooltip: 'Best for variable or unpredictable traffic. No upfront commitment.',
            },
            {
              value: 'reserved-50',
              label: 'Reserved 50 CU',
              description: '50 read/write CU · predictable cost',
              cost: '~$45/mo',
              provider: 'alibaba',
            },
            {
              value: 'reserved-100',
              label: 'Reserved 100 CU',
              description: '100 read/write CU · steady traffic',
              cost: '~$85/mo',
              provider: 'alibaba',
            },
            {
              value: 'reserved-200',
              label: 'Reserved 200 CU',
              description: '200 read/write CU · moderate workloads',
              cost: '~$160/mo',
              provider: 'alibaba',
            },
            {
              value: 'reserved-500',
              label: 'Reserved 500 CU',
              description: '500 read/write CU · heavy workloads',
              cost: '~$380/mo',
              provider: 'alibaba',
            },
            {
              value: 'reserved-1000',
              label: 'Reserved 1,000 CU',
              description: '1,000 read/write CU · high throughput',
              cost: '~$720/mo',
              provider: 'alibaba',
            },
            { value: 'custom', label: 'Custom CU', description: 'Enter specific capacity units' },
          ],
          customInput: { type: 'number', unit: 'CU', min: 1, max: 100000, step: 10, placeholder: 'e.g. 300' },
        },
      ],
    },
    {
      id: 'autonomous-db',
      name: 'Autonomous Database',
      description: 'Self-managing Oracle database with automated tuning and patching',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['oci'],
      implementations: [
        {
          provider: 'oci',
          resource_type: 'oci:database:AutonomousDatabase',
          display_name: 'Autonomous Database',
        },
      ],
      keywords: ['autonomous', 'oracle', 'adb', 'self-managing', 'oci'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'purpose',
          label: 'Workload type',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Workload type — determines optimization and features',
          default: 'atp',
          optionDetails: [
            {
              value: 'atp',
              label: 'Transaction Processing',
              description: 'OLTP — orders, accounts, real-time apps',
              provider: 'oci',
            },
            {
              value: 'adw',
              label: 'Data Warehouse',
              description: 'OLAP — analytics, reporting, BI',
              provider: 'oci',
            },
            {
              value: 'ajd',
              label: 'JSON Database',
              description: 'Document store — MongoDB-compatible',
              provider: 'oci',
            },
            { value: 'apex', label: 'APEX Service', description: 'Low-code Oracle APEX apps', provider: 'oci' },
          ],
        },
        {
          name: 'size',
          label: 'Compute',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'OCPU count and storage — determines query speed and capacity',
          default: '1-ocpu',
          optionDetails: [
            {
              value: 'always-free',
              label: 'Always Free',
              description: '1 OCPU · 20 GB storage',
              cost: 'Free forever',
              provider: 'oci',
            },
            {
              value: '1-ocpu',
              label: '1 OCPU',
              description: '1 OCPU · 1 TB storage',
              cost: '~$175/mo',
              provider: 'oci',
            },
            {
              value: '2-ocpu',
              label: '2 OCPU',
              description: '2 OCPU · 1 TB storage',
              cost: '~$350/mo',
              provider: 'oci',
            },
            {
              value: '4-ocpu',
              label: '4 OCPU',
              description: '4 OCPU · 2 TB storage',
              cost: '~$700/mo',
              provider: 'oci',
            },
            {
              value: '8-ocpu',
              label: '8 OCPU',
              description: '8 OCPU · 4 TB storage',
              cost: '~$1,400/mo',
              provider: 'oci',
            },
            {
              value: '16-ocpu',
              label: '16 OCPU',
              description: '16 OCPU · 8 TB storage',
              cost: '~$2,800/mo',
              provider: 'oci',
            },
          ],
        },
      ],
    },
    {
      id: 'do-managed-db',
      name: 'Managed Database',
      description: 'Simple managed database with automatic failover',
      icon: 'Database',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['digitalocean'],
      implementations: [
        {
          provider: 'digitalocean',
          resource_type: 'digitalocean:database:Cluster',
          display_name: 'Managed Database Cluster',
        },
      ],
      keywords: ['managed', 'database', 'digitalocean', 'postgres', 'mysql', 'redis'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this database',
          placeholder: 'My Database',
        },
        {
          name: 'engine',
          label: 'What type of database?',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Choose the database engine',
          default: 'pg',
          optionDetails: [
            { value: 'pg', label: 'PostgreSQL', description: 'Relational — most popular', provider: 'digitalocean' },
            { value: 'mysql', label: 'MySQL', description: 'Relational — widely used', provider: 'digitalocean' },
            { value: 'redis', label: 'Redis', description: 'In-memory cache & key-value', provider: 'digitalocean' },
            { value: 'mongodb', label: 'MongoDB', description: 'NoSQL document store', provider: 'digitalocean' },
            { value: 'kafka', label: 'Kafka', description: 'Event streaming', provider: 'digitalocean' },
          ],
        },
        {
          name: 'size',
          label: 'Instance size',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Database node size',
          default: 'db-s-1vcpu-1gb',
          optionDetails: [
            {
              value: 'db-s-1vcpu-1gb',
              label: '1 vCPU / 1 GB',
              description: '1 vCPU · 1 GB RAM · 10 GB disk',
              cost: '~$15/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-1vcpu-2gb',
              label: '1 vCPU / 2 GB',
              description: '1 vCPU · 2 GB RAM · 25 GB disk',
              cost: '~$30/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-2vcpu-4gb',
              label: '2 vCPU / 4 GB',
              description: '2 vCPU · 4 GB RAM · 38 GB disk',
              cost: '~$60/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-4vcpu-8gb',
              label: '4 vCPU / 8 GB',
              description: '4 vCPU · 8 GB RAM · 115 GB disk',
              cost: '~$120/mo',
              provider: 'digitalocean',
            },
            {
              value: 'db-s-8vcpu-16gb',
              label: '8 vCPU / 16 GB',
              description: '8 vCPU · 16 GB RAM · 270 GB disk',
              cost: '~$240/mo',
              provider: 'digitalocean',
            },
          ],
        },
        {
          name: 'production',
          label: 'Production-ready?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Turns on automatic backups and failover so your data is safe',
          default: false,
        },
      ],
    },
    {
      id: 'vector-db',
      name: 'Vector Database',
      description: 'Store and search vector embeddings for AI/ML applications',
      icon: 'Compass',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        {
          provider: 'aws',
          resource_type: 'aws:opensearch:Domain',
          display_name: 'OpenSearch (k-NN)',
        },
        {
          provider: 'gcp',
          resource_type: 'gcp:aiplatform:FeaturestoreEntitytype',
          display_name: 'Vertex AI Vector Search',
        },
        {
          provider: 'azure',
          resource_type: 'azure:search:Service',
          display_name: 'Azure AI Search',
        },
      ],
      keywords: ['vector', 'embedding', 'pinecone', 'weaviate', 'qdrant', 'pgvector', 'chromadb', 'milvus'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this vector store',
          placeholder: 'My Vector Store',
        },
        {
          name: 'size',
          label: 'Cluster size',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Cluster capacity — determines vectors stored and query speed',
          default: 'os-t3.small',
          optionDetails: [
            {
              value: 'os-t3.small',
              label: 't3.small.search',
              description: '2 vCPU · 2 GB · ~100K vectors',
              cost: '~$26/mo',
              provider: 'aws',
            },
            {
              value: 'os-m6g.large',
              label: 'm6g.large.search',
              description: '2 vCPU · 8 GB · ~1M vectors',
              cost: '~$97/mo',
              provider: 'aws',
            },
            {
              value: 'os-r6g.xlarge',
              label: 'r6g.xlarge.search',
              description: '4 vCPU · 32 GB · ~5M vectors',
              cost: '~$292/mo',
              provider: 'aws',
            },
            {
              value: 'gcp-basic',
              label: 'Basic',
              description: '2 vCPU · 8 GB · Vertex AI Search',
              cost: '~$50/mo',
              provider: 'gcp',
            },
            {
              value: 'gcp-standard',
              label: 'Standard',
              description: '4 vCPU · 16 GB · Vertex AI Search',
              cost: '~$150/mo',
              provider: 'gcp',
            },
            {
              value: 'azure-basic',
              label: 'Basic',
              description: '1 replica · 2 GB · ~50K vectors',
              cost: '~$75/mo',
              provider: 'azure',
            },
            {
              value: 'azure-s1',
              label: 'Standard S1',
              description: '1 replica · 25 GB · ~1M vectors',
              cost: '~$250/mo',
              provider: 'azure',
            },
            {
              value: 'azure-s2',
              label: 'Standard S2',
              description: '1 replica · 100 GB · ~5M vectors',
              cost: '~$1,000/mo',
              provider: 'azure',
            },
          ],
        },
        {
          name: 'engine',
          label: 'Vector engine',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Which vector engine to use',
          default: 'pgvector',
          tooltip:
            'pgvector requires no extra infra if you already have PostgreSQL. Pinecone is fully managed SaaS. Others are self-hosted open-source options with different performance characteristics.',
          optionDetails: [
            {
              value: 'pinecone',
              label: 'Pinecone',
              description: 'Managed SaaS — easiest to start',
              tooltip: 'Fully managed, no infrastructure to run. Serverless or pod-based pricing.',
            },
            {
              value: 'weaviate',
              label: 'Weaviate',
              description: 'Open-source — AI-native with modules',
              tooltip: 'Built-in vectorization modules. Supports hybrid search (vector + keyword).',
            },
            {
              value: 'qdrant',
              label: 'Qdrant',
              description: 'Open-source — Rust-based, fast',
              tooltip: 'High performance written in Rust. Good for large-scale similarity search.',
            },
            {
              value: 'pgvector',
              label: 'pgvector',
              description: 'PostgreSQL extension — no extra infra',
              tooltip: 'Add vector search to existing PostgreSQL. Simplest option if you already use Postgres.',
            },
            {
              value: 'chromadb',
              label: 'ChromaDB',
              description: 'Open-source — Python-first, simple',
              tooltip: 'Easy to get started. Best for prototyping and small-scale applications.',
            },
            {
              value: 'milvus',
              label: 'Milvus',
              description: 'Open-source — large-scale production',
              tooltip: 'Designed for billion-scale vector data. GPU-accelerated search available.',
            },
          ],
        },
      ],
    },
    {
      id: 'data-warehouse',
      name: 'Data Warehouse',
      description: 'Columnar analytics database for large-scale queries',
      icon: 'Warehouse',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:redshift:Cluster', display_name: 'Redshift' },
        { provider: 'gcp', resource_type: 'gcp:bigquery:Dataset', display_name: 'BigQuery' },
        {
          provider: 'azure',
          resource_type: 'azure:synapse:Workspace',
          display_name: 'Synapse Analytics',
        },
      ],
      keywords: ['warehouse', 'redshift', 'bigquery', 'snowflake', 'clickhouse', 'analytics', 'olap'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this data warehouse',
          placeholder: 'My Warehouse',
        },
        {
          name: 'size',
          label: 'Compute size',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Cluster/compute capacity for queries',
          default: 'dc2.large',
          optionDetails: [
            {
              value: 'dc2.large',
              label: 'dc2.large (2-node)',
              description: '2 vCPU · 15 GB RAM · 160 GB SSD each',
              cost: '~$360/mo',
              provider: 'aws',
            },
            {
              value: 'dc2.large-4',
              label: 'dc2.large (4-node)',
              description: '4 nodes · 640 GB total',
              cost: '~$720/mo',
              provider: 'aws',
            },
            {
              value: 'ra3.xlplus',
              label: 'ra3.xlplus (2-node)',
              description: '4 vCPU · 32 GB · managed storage',
              cost: '~$1,560/mo',
              provider: 'aws',
            },
            {
              value: 'bq-on-demand',
              label: 'On-demand',
              description: 'Pay per query · $6.25/TB scanned',
              cost: '~$6.25/TB',
              provider: 'gcp',
            },
            {
              value: 'bq-flat-100',
              label: 'Flat-rate 100 slots',
              description: '100 compute slots · dedicated',
              cost: '~$2,000/mo',
              provider: 'gcp',
            },
            {
              value: 'bq-editions',
              label: 'Standard edition',
              description: 'Auto-scaling slots',
              cost: '~$0.04/slot-hr',
              provider: 'gcp',
            },
            {
              value: 'synapse-dw100',
              label: 'DW100c',
              description: '1 compute node · 60 TB storage',
              cost: '~$1.20/hr',
              provider: 'azure',
            },
            {
              value: 'synapse-dw200',
              label: 'DW200c',
              description: '2 compute nodes · 60 TB storage',
              cost: '~$2.40/hr',
              provider: 'azure',
            },
            {
              value: 'synapse-serverless',
              label: 'Serverless',
              description: 'Pay per TB processed',
              cost: '~$5/TB',
              provider: 'azure',
            },
          ],
        },
        {
          name: 'engine',
          label: 'Analytics engine',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Which analytics engine to use',
          default: 'native',
          optionDetails: [
            {
              value: 'native',
              label: 'Provider native',
              description: 'Redshift / BigQuery / Synapse based on cloud',
            },
            { value: 'snowflake', label: 'Snowflake', description: 'Cross-cloud, auto-scaling warehouse' },
            { value: 'clickhouse', label: 'ClickHouse', description: 'Open-source columnar OLAP, self-hosted' },
            { value: 'databricks', label: 'Databricks', description: 'Unified analytics + ML lakehouse' },
          ],
        },
      ],
    },
    {
      id: 'search-engine',
      name: 'Search Engine',
      description: 'Full-text search and analytics engine',
      icon: 'Search',
      category: 'database',
      behavior: 'stateful' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:opensearch:Domain', display_name: 'OpenSearch' },
        {
          provider: 'gcp',
          resource_type: 'gcp:discoveryengine:SearchEngine',
          display_name: 'Vertex AI Search',
        },
        {
          provider: 'azure',
          resource_type: 'azure:search:Service',
          display_name: 'Azure Cognitive Search',
        },
      ],
      keywords: ['search', 'elasticsearch', 'opensearch', 'algolia', 'fulltext'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this search engine',
          placeholder: 'My Search',
        },
        {
          name: 'size',
          label: 'Cluster size',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'Node size — determines index capacity and query throughput',
          default: 'os-t3.small',
          optionDetails: [
            {
              value: 'os-t3.small',
              label: 't3.small.search',
              description: '2 vCPU · 2 GB RAM',
              cost: '~$26/mo',
              provider: 'aws',
            },
            {
              value: 'os-t3.medium',
              label: 't3.medium.search',
              description: '2 vCPU · 4 GB RAM',
              cost: '~$52/mo',
              provider: 'aws',
            },
            {
              value: 'os-m6g.large',
              label: 'm6g.large.search',
              description: '2 vCPU · 8 GB RAM',
              cost: '~$97/mo',
              provider: 'aws',
            },
            {
              value: 'os-r6g.xlarge',
              label: 'r6g.xlarge.search',
              description: '4 vCPU · 32 GB RAM',
              cost: '~$292/mo',
              provider: 'aws',
            },
            {
              value: 'gcp-basic',
              label: 'Basic',
              description: 'Up to 10K documents',
              cost: 'Free tier',
              provider: 'gcp',
            },
            {
              value: 'gcp-enterprise',
              label: 'Enterprise',
              description: 'Unlimited docs · advanced features',
              cost: '~$3/1K queries',
              provider: 'gcp',
            },
            {
              value: 'azure-free',
              label: 'Free',
              description: '50 MB storage · 3 indexes',
              cost: 'Free',
              provider: 'azure',
            },
            {
              value: 'azure-basic',
              label: 'Basic',
              description: '2 GB storage · 15 indexes',
              cost: '~$75/mo',
              provider: 'azure',
            },
            {
              value: 'azure-s1',
              label: 'Standard S1',
              description: '25 GB storage · 50 indexes',
              cost: '~$250/mo',
              provider: 'azure',
            },
          ],
        },
        {
          name: 'engine',
          label: 'Search engine',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Which search engine to use',
          default: 'opensearch',
          optionDetails: [
            { value: 'opensearch', label: 'OpenSearch', description: 'AWS-managed — fork of Elasticsearch' },
            {
              value: 'elasticsearch',
              label: 'Elasticsearch',
              description: 'Original full-text engine — Elastic Cloud',
            },
            { value: 'algolia', label: 'Algolia', description: 'SaaS — instant search, easy setup' },
            { value: 'typesense', label: 'Typesense', description: 'Open-source — typo-tolerant, fast' },
            { value: 'meilisearch', label: 'Meilisearch', description: 'Open-source — developer-friendly' },
          ],
        },
      ],
    },
  ],
};
