/**
 * High-level resource category: NETWORKING.
 *
 * Load balancers, public endpoints, VPCs, subnets, CDNs, DNS, API gateways.
 *
 * SIZE EXCEPTION: this file is intentionally >500 LOC because it is dominated
 * by data — per-resource property catalogues and provider implementations
 * total ~560 LOC of pure literal. The split-by-category boundary is the
 * stable seam; further fragmentation would not improve readability.
 *
 * The exported `networking: HighLevelCategory` is consumed by `../high-level-resources.ts`
 * which assembles it into `HIGH_LEVEL_CATEGORIES`. The shape and content are
 * byte-identical to what was previously inlined there.
 */

// `NodeBehavior` is imported because the data literal uses `behavior: '...' as NodeBehavior` casts.
import type { HighLevelCategory, NodeBehavior } from '../types';
export type { NodeBehavior };

export const networking: HighLevelCategory = {
  id: 'networking',
  name: 'Networking',
  description: 'Load balancers, CDN, DNS, and VPC',
  icon: 'Network',
  resources: [
    {
      id: 'public-endpoint',
      name: 'Public Endpoint',
      description:
        'Public HTTPS entry point with managed SSL certificate. Connect to one or more services and route traffic by subdomain (api.example.com, app.example.com, …).',
      icon: 'Globe',
      category: 'networking',
      behavior: 'connector' as NodeBehavior,
      providers: ['gcp', 'aws', 'azure'],
      implementations: [
        {
          provider: 'gcp',
          resource_type: 'gcp:compute:GlobalForwardingRule',
          display_name: 'Global Load Balancer',
        },
        {
          provider: 'aws',
          resource_type: 'aws:elasticloadbalancingv2:LoadBalancer',
          display_name: 'Application Load Balancer',
        },
        {
          provider: 'azure',
          resource_type: 'azure:network:FrontDoor',
          display_name: 'Front Door',
        },
      ],
      keywords: ['domain', 'https', 'ssl', 'certificate', 'public', 'internet', 'load balancer', 'subdomain'],
      properties: [
        {
          name: 'domain',
          label: 'Domain',
          type: 'string',
          required: false,
          tier: 'essential',
          description:
            'Root domain you own (e.g. example.com). Leave empty for IP-only HTTP deploys without a certificate.',
          placeholder: 'example.com',
        },
        {
          name: 'enableHttps',
          label: 'Enable HTTPS',
          type: 'boolean',
          required: false,
          tier: 'essential',
          description: 'Serve traffic over HTTPS with a managed SSL certificate. Turn off for plain HTTP on the IP.',
          default: true,
        },
        {
          name: 'autoProvisionCert',
          label: 'Auto-provision SSL certificate',
          type: 'boolean',
          required: false,
          tier: 'essential',
          description:
            'Let the cloud provider automatically issue and renew a managed certificate for your domain(s). Uncheck to bring your own.',
          default: true,
        },
        {
          name: 'sslCertificateId',
          label: 'Existing certificate ID',
          type: 'string',
          required: false,
          tier: 'advanced',
          description:
            'Use an existing SSL certificate instead of auto-provisioning one. Only used when auto-provision is off.',
          placeholder: 'projects/.../sslCertificates/...',
        },
        {
          name: 'redirectHttpToHttps',
          label: 'Redirect HTTP → HTTPS',
          type: 'boolean',
          required: false,
          tier: 'essential',
          description: 'Automatically redirect visitors from http:// to https://.',
          default: true,
        },
      ],
    },
    {
      id: 'vpc-network',
      name: 'Virtual Network',
      description: 'Isolated network that contains subnets and resources',
      icon: 'Network',
      category: 'networking',
      behavior: 'container' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:ec2:Vpc', display_name: 'VPC' },
        { provider: 'gcp', resource_type: 'gcp:compute:Network', display_name: 'VPC Network' },
        {
          provider: 'azure',
          resource_type: 'azure:network:VirtualNetwork',
          display_name: 'Virtual Network',
        },
      ],
      keywords: ['vpc', 'vnet', 'network', 'virtual', 'subnet'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this network',
          placeholder: 'My Network',
        },
        {
          name: 'size',
          label: 'Size',
          type: 'select',
          required: true,
          tier: 'essential',
          description: 'How many services will live in this network?',
          options: ['Small — a few services', 'Medium — a typical app', 'Large — many services and teams'],
          default: 'Small — a few services',
        },
        {
          name: 'cidr',
          label: 'IP range',
          type: 'string',
          required: false,
          tier: 'advanced',
          description: 'Advanced: custom IP address range for this network',
          default: '10.0.0.0/16',
          placeholder: 'e.g. 10.0.0.0/16',
        },
      ],
    },
    {
      id: 'subnet',
      name: 'Subnet',
      description: 'Network subdivision within a VPC',
      icon: 'Layers',
      category: 'networking',
      behavior: 'container' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:ec2:Subnet', display_name: 'Subnet' },
        { provider: 'gcp', resource_type: 'gcp:compute:Subnetwork', display_name: 'Subnetwork' },
        { provider: 'azure', resource_type: 'azure:network:Subnet', display_name: 'Subnet' },
      ],
      keywords: ['subnet', 'subnetwork', 'az', 'availability'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this subnet',
          placeholder: 'My Subnet',
        },
        {
          name: 'internet_access',
          label: 'Can reach the internet?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Allow resources in this subnet to access the internet',
          default: false,
        },
        {
          name: 'cidr',
          label: 'IP range',
          type: 'string',
          required: false,
          tier: 'advanced',
          description: 'Advanced: custom IP address range for this subnet',
          default: '10.0.1.0/24',
          placeholder: 'e.g. 10.0.1.0/24',
        },
      ],
    },
    {
      id: 'load-balancer',
      name: 'Load Balancer',
      description: 'Distribute traffic across multiple targets',
      icon: 'GitBranch',
      category: 'networking',
      behavior: 'connector' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure', 'kubernetes'],
      implementations: [
        {
          provider: 'aws',
          resource_type: 'aws:elasticloadbalancingv2:LoadBalancer',
          display_name: 'ALB/NLB',
        },
        {
          provider: 'gcp',
          resource_type: 'gcp:compute:ForwardingRule',
          display_name: 'Cloud Load Balancer',
        },
        {
          provider: 'azure',
          resource_type: 'azure:network:LoadBalancer',
          display_name: 'Azure Load Balancer',
        },
        {
          provider: 'kubernetes',
          resource_type: 'kubernetes:core/v1:Service',
          display_name: 'K8s Service (LoadBalancer)',
        },
      ],
      keywords: ['load', 'balancer', 'alb', 'elb', 'nlb', 'lb'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this load balancer',
          placeholder: 'My Load Balancer',
        },
        {
          name: 'type',
          label: 'Load balancer type',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'Type of load balancer — determines protocol support and features',
          default: 'alb',
          optionDetails: [
            {
              value: 'alb',
              label: 'Application LB (ALB)',
              description: 'HTTP/HTTPS · path routing · WebSocket',
              cost: '~$22/mo + LCU',
              provider: 'aws',
            },
            {
              value: 'nlb',
              label: 'Network LB (NLB)',
              description: 'TCP/UDP · ultra-low latency · static IP',
              cost: '~$22/mo + LCU',
              provider: 'aws',
            },
            {
              value: 'gcp-http',
              label: 'HTTP(S) LB',
              description: 'Global HTTP/HTTPS · URL maps',
              cost: '~$18/mo + data',
              provider: 'gcp',
            },
            {
              value: 'gcp-tcp',
              label: 'TCP/UDP LB',
              description: 'Regional · network traffic',
              cost: '~$18/mo + data',
              provider: 'gcp',
            },
            {
              value: 'azure-standard',
              label: 'Standard LB',
              description: 'TCP/UDP · zone-redundant',
              cost: '~$18/mo + rules',
              provider: 'azure',
            },
            {
              value: 'azure-app-gw',
              label: 'Application Gateway',
              description: 'HTTP/HTTPS · WAF · SSL offload',
              cost: '~$55/mo + data',
              provider: 'azure',
            },
            {
              value: 'k8s-service',
              label: 'K8s Service',
              description: 'LoadBalancer type service',
              provider: 'kubernetes',
            },
            {
              value: 'k8s-ingress',
              label: 'K8s Ingress',
              description: 'HTTP routing · path-based',
              provider: 'kubernetes',
            },
          ],
        },
        {
          name: 'internal_only',
          label: 'Internal only?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Only accessible by other services in your network (not the public internet)',
          default: false,
        },
      ],
    },
    {
      id: 'cdn',
      name: 'CDN',
      description: 'Content delivery network for global distribution',
      icon: 'Globe',
      category: 'networking',
      behavior: 'connector' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        {
          provider: 'aws',
          resource_type: 'aws:cloudfront:Distribution',
          display_name: 'CloudFront',
        },
        {
          provider: 'gcp',
          resource_type: 'gcp:compute:GlobalForwardingRule',
          display_name: 'Cloud CDN',
        },
        { provider: 'azure', resource_type: 'azure:cdn:Endpoint', display_name: 'Azure CDN' },
      ],
      keywords: ['cdn', 'cloudfront', 'cloudflare', 'fastly', 'akamai'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this CDN',
          placeholder: 'My CDN',
        },
        {
          name: 'tier',
          label: 'Price class',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'CDN edge locations — more locations = faster worldwide but costs more',
          default: 'cf-all',
          optionDetails: [
            {
              value: 'cf-100',
              label: 'Price Class 100',
              description: 'US, Canada, Europe only',
              cost: '~$0.085/GB',
              provider: 'aws',
            },
            {
              value: 'cf-200',
              label: 'Price Class 200',
              description: '+ Asia, Africa, Middle East',
              cost: '~$0.120/GB',
              provider: 'aws',
            },
            {
              value: 'cf-all',
              label: 'All Edge Locations',
              description: 'Global — all regions',
              cost: '~$0.085–0.170/GB',
              provider: 'aws',
            },
            {
              value: 'gcp-standard',
              label: 'Standard',
              description: 'Cloud CDN — cache at Google edge',
              cost: '~$0.08/GB',
              provider: 'gcp',
            },
            {
              value: 'gcp-premium',
              label: 'Premium',
              description: 'Cloud CDN — premium network tier',
              cost: '~$0.12/GB',
              provider: 'gcp',
            },
            {
              value: 'azure-standard',
              label: 'Standard Microsoft',
              description: 'Microsoft CDN network',
              cost: '~$0.081/GB',
              provider: 'azure',
            },
            {
              value: 'azure-premium-verizon',
              label: 'Premium Verizon',
              description: 'Advanced rules, analytics',
              cost: '~$0.150/GB',
              provider: 'azure',
            },
            {
              value: 'azure-afd',
              label: 'Azure Front Door',
              description: 'Global LB + CDN combined',
              cost: '~$35/mo + $0.08/GB',
              provider: 'azure',
            },
          ],
        },
        {
          name: 'custom_domain',
          label: 'Custom domain',
          type: 'string',
          required: false,
          tier: 'detailed',
          description: 'Use your own domain for the CDN',
          placeholder: 'e.g. cdn.example.com',
        },
      ],
    },
    {
      id: 'api-gateway',
      name: 'API Gateway',
      description: 'Managed API endpoint with routing and auth',
      icon: 'Server',
      category: 'networking',
      behavior: 'connector' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        { provider: 'aws', resource_type: 'aws:apigatewayv2:Api', display_name: 'API Gateway' },
        { provider: 'gcp', resource_type: 'gcp:apigateway:Gateway', display_name: 'API Gateway' },
        {
          provider: 'azure',
          resource_type: 'azure:apimanagement:Api',
          display_name: 'API Management',
        },
      ],
      keywords: ['api', 'gateway', 'rest', 'http', 'websocket'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this gateway',
          placeholder: 'My API Gateway',
        },
        {
          name: 'protocol',
          label: 'Protocol',
          type: 'select',
          required: false,
          tier: 'essential',
          description: 'API protocol type — determines features and pricing',
          default: 'http',
          optionDetails: [
            {
              value: 'http',
              label: 'HTTP API',
              description: 'Simple, low-cost HTTP routing',
              cost: '~$1.00/M requests',
              provider: 'aws',
            },
            {
              value: 'rest',
              label: 'REST API',
              description: 'Full-featured · API keys, caching, WAF',
              cost: '~$3.50/M requests',
              provider: 'aws',
            },
            {
              value: 'websocket',
              label: 'WebSocket',
              description: 'Persistent bi-directional connections',
              cost: '~$1.00/M messages',
              provider: 'aws',
            },
            {
              value: 'gcp-api-gw',
              label: 'API Gateway',
              description: 'Managed API routing',
              cost: '~$3/M calls',
              provider: 'gcp',
            },
            {
              value: 'azure-consumption',
              label: 'Consumption',
              description: 'Pay-per-call · auto-scaling',
              cost: '~$3.50/M calls',
              provider: 'azure',
            },
            {
              value: 'azure-standard',
              label: 'Standard v2',
              description: 'Fixed capacity · full features',
              cost: '~$170/mo',
              provider: 'azure',
            },
          ],
        },
        {
          name: 'routes',
          label: 'Routes',
          type: 'list',
          required: false,
          tier: 'essential',
          description: 'URL paths this gateway should handle',
          placeholder: 'e.g. /api/users',
          addLabel: 'Add a route',
        },
        {
          name: 'login_required',
          label: 'Require login?',
          type: 'boolean',
          required: false,
          tier: 'detailed',
          description: 'Require authentication before requests reach your services',
          default: false,
        },
      ],
    },
    {
      id: 'dns-zone',
      name: 'DNS Zone',
      description: 'Manage DNS records for your domain',
      icon: 'Globe',
      category: 'networking',
      behavior: 'singleton' as NodeBehavior,
      providers: ['aws', 'gcp', 'azure'],
      implementations: [
        {
          provider: 'aws',
          resource_type: 'aws:route53:Zone',
          display_name: 'Route 53 Hosted Zone',
        },
        { provider: 'gcp', resource_type: 'gcp:dns:ManagedZone', display_name: 'Cloud DNS Zone' },
        { provider: 'azure', resource_type: 'azure:dns:Zone', display_name: 'Azure DNS Zone' },
      ],
      keywords: ['dns', 'route53', 'domain', 'zone', 'cloudflare'],
      properties: [
        {
          name: 'name',
          label: 'Name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'A friendly name for this DNS zone',
          placeholder: 'My Domain',
        },
        {
          name: 'domain',
          label: 'Domain name',
          type: 'string',
          required: true,
          tier: 'essential',
          description: 'The domain you want to manage',
          placeholder: 'e.g. example.com',
        },
        {
          name: 'subdomains',
          label: 'Subdomains',
          type: 'list',
          required: false,
          tier: 'detailed',
          description: 'Subdomains to set up (we will create the DNS records)',
          placeholder: 'e.g. api, www, app',
          addLabel: 'Add a subdomain',
        },
      ],
    },
  ],
};
