/**
 * High-level resource category: STORAGE.
 *
 * Object stores, file shares, and bucket-style persistence layers.
 *
 * SIZE EXCEPTION: this file is intentionally >200 LOC because it is dominated
 * by data — per-resource property catalogues and provider implementations
 * total ~450 LOC of pure literal. The split-by-category boundary is the
 * stable seam; further fragmentation would not improve readability.
 *
 * The exported `storage: HighLevelCategory` is consumed by `../high-level-resources.ts`
 * which assembles it into `HIGH_LEVEL_CATEGORIES`. The shape and content are
 * byte-identical to what was previously inlined there.
 */

// `NodeBehavior` is imported because the data literal uses `behavior: '...' as NodeBehavior` casts.
import type { HighLevelCategory, NodeBehavior } from '../types.js';
export type { NodeBehavior };

export const storage: HighLevelCategory = 
  {
    id: 'storage',
    name: 'Storage',
    description: 'File and object storage',
    icon: 'HardDrive',
    resources: [
      {
        id: 'object-storage',
        name: 'Object Storage',
        description: 'Store files, images, videos, and backups',
        icon: 'Archive',
        category: 'storage',
        behavior: 'stateful' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure', 'alibaba', 'oci', 'digitalocean'],
        implementations: [
          { provider: 'aws', resource_type: 'aws:s3:Bucket', display_name: 'S3 Bucket' },
          {
            provider: 'gcp',
            resource_type: 'gcp:storage:Bucket',
            display_name: 'Cloud Storage Bucket',
          },
          {
            provider: 'azure',
            resource_type: 'azure:storage:Container',
            display_name: 'Azure Blob Container',
          },
          { provider: 'alibaba', resource_type: 'alibaba:oss:Bucket', display_name: 'OSS Bucket' },
          {
            provider: 'oci',
            resource_type: 'oci:objectstorage:Bucket',
            display_name: 'OCI Object Storage',
          },
          {
            provider: 'digitalocean',
            resource_type: 'digitalocean:spaces:Bucket',
            display_name: 'Spaces Bucket',
          },
        ],
        keywords: ['s3', 'bucket', 'blob', 'storage', 'gcs', 'object'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this storage bucket',
            placeholder: 'My Files',
          },
          {
            name: 'public',
            label: 'Publicly accessible?',
            type: 'boolean',
            required: false,
            tier: 'essential',
            description: 'Allow anyone on the internet to view these files',
            default: false,
          },
          {
            name: 'storage_class',
            label: 'Storage class',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Access frequency — affects cost and retrieval speed',
            default: 'standard',
            optionDetails: [
              {
                value: 'standard',
                label: 'Standard',
                description: 'Frequently accessed data',
                cost: '~$0.023/GB/mo',
                provider: 'aws',
              },
              {
                value: 'standard-ia',
                label: 'Infrequent Access',
                description: 'Accessed < 1x/month · lower storage cost',
                cost: '~$0.0125/GB/mo',
                provider: 'aws',
              },
              {
                value: 'glacier',
                label: 'Glacier',
                description: 'Archive · minutes-to-hours retrieval',
                cost: '~$0.004/GB/mo',
                provider: 'aws',
              },
              {
                value: 'glacier-deep',
                label: 'Glacier Deep Archive',
                description: 'Long-term archive · 12-hour retrieval',
                cost: '~$0.00099/GB/mo',
                provider: 'aws',
              },
              {
                value: 'gcp-standard',
                label: 'Standard',
                description: 'Frequently accessed data',
                cost: '~$0.020/GB/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-nearline',
                label: 'Nearline',
                description: 'Accessed < 1x/month',
                cost: '~$0.010/GB/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-coldline',
                label: 'Coldline',
                description: 'Accessed < 1x/quarter',
                cost: '~$0.004/GB/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-archive',
                label: 'Archive',
                description: 'Accessed < 1x/year',
                cost: '~$0.0012/GB/mo',
                provider: 'gcp',
              },
              {
                value: 'azure-hot',
                label: 'Hot',
                description: 'Frequently accessed data',
                cost: '~$0.018/GB/mo',
                provider: 'azure',
              },
              {
                value: 'azure-cool',
                label: 'Cool',
                description: 'Infrequently accessed · 30-day min',
                cost: '~$0.010/GB/mo',
                provider: 'azure',
              },
              {
                value: 'azure-archive',
                label: 'Archive',
                description: 'Rarely accessed · hours to retrieve',
                cost: '~$0.002/GB/mo',
                provider: 'azure',
              },
            ],
          },
          {
            name: 'versioning',
            label: 'Keep old versions of files?',
            type: 'boolean',
            required: false,
            tier: 'detailed',
            description: 'Keep old versions of files — enables recovery from accidental deletes',
            default: false,
          },
        ],
      },
      {
        id: 'oss',
        name: 'OSS',
        description: 'Alibaba Cloud object storage with China-optimized CDN',
        icon: 'HardDrive',
        category: 'storage',
        behavior: 'stateful' as NodeBehavior,
        providers: ['alibaba'],
        implementations: [{ provider: 'alibaba', resource_type: 'alibaba:oss:Bucket', display_name: 'OSS Bucket' }],
        keywords: ['oss', 'object', 'storage', 'alibaba', 'bucket'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this storage bucket',
            placeholder: 'My Files',
          },
          {
            name: 'storage_class',
            label: 'Storage class',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Access frequency — affects cost and retrieval speed',
            default: 'oss-standard',
            optionDetails: [
              {
                value: 'oss-standard',
                label: 'Standard',
                description: 'Frequently accessed data',
                cost: '~$0.02/GB/mo',
                provider: 'alibaba',
              },
              {
                value: 'oss-ia',
                label: 'Infrequent Access',
                description: 'Accessed < 1x/month · 30-day min',
                cost: '~$0.008/GB/mo',
                provider: 'alibaba',
              },
              {
                value: 'oss-archive',
                label: 'Archive',
                description: 'Rarely accessed · 1-minute restore',
                cost: '~$0.005/GB/mo',
                provider: 'alibaba',
              },
              {
                value: 'oss-cold-archive',
                label: 'Cold Archive',
                description: 'Long-term archive · hours to restore',
                cost: '~$0.002/GB/mo',
                provider: 'alibaba',
              },
            ],
          },
          {
            name: 'public',
            label: 'Publicly accessible?',
            type: 'boolean',
            required: false,
            tier: 'essential',
            description: 'Allow anyone on the internet to view these files',
            default: false,
          },
        ],
      },
      {
        id: 'oci-object-storage',
        name: 'OCI Object Storage',
        description: 'Enterprise object storage with automatic tiering',
        icon: 'HardDrive',
        category: 'storage',
        behavior: 'stateful' as NodeBehavior,
        providers: ['oci'],
        implementations: [
          {
            provider: 'oci',
            resource_type: 'oci:objectstorage:Bucket',
            display_name: 'OCI Object Storage Bucket',
          },
        ],
        keywords: ['oci', 'object', 'storage', 'oracle', 'bucket'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this storage bucket',
            placeholder: 'My Files',
          },
          {
            name: 'storage_class',
            label: 'Storage tier',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Access frequency — affects cost and retrieval speed',
            default: 'oci-standard',
            optionDetails: [
              {
                value: 'oci-standard',
                label: 'Standard',
                description: 'Frequently accessed · hot data',
                cost: '~$0.0255/GB/mo',
                provider: 'oci',
              },
              {
                value: 'oci-infrequent',
                label: 'Infrequent Access',
                description: 'Accessed < 1x/month',
                cost: '~$0.01/GB/mo',
                provider: 'oci',
              },
              {
                value: 'oci-archive',
                label: 'Archive',
                description: 'Rarely accessed · 1-hour restore',
                cost: '~$0.004/GB/mo',
                provider: 'oci',
              },
            ],
          },
          {
            name: 'public',
            label: 'Publicly accessible?',
            type: 'boolean',
            required: false,
            tier: 'essential',
            description: 'Allow anyone on the internet to view these files',
            default: false,
          },
          {
            name: 'auto_tiering',
            label: 'Auto-tiering?',
            type: 'boolean',
            required: false,
            tier: 'detailed',
            description: 'Automatically move objects to cheaper tiers based on access patterns',
            default: false,
          },
        ],
      },
      {
        id: 'do-spaces',
        name: 'Spaces',
        description: 'S3-compatible object storage with built-in CDN',
        icon: 'HardDrive',
        category: 'storage',
        behavior: 'stateful' as NodeBehavior,
        providers: ['digitalocean'],
        implementations: [
          {
            provider: 'digitalocean',
            resource_type: 'digitalocean:spaces:Bucket',
            display_name: 'Spaces Bucket',
          },
        ],
        keywords: ['spaces', 'object', 'storage', 'digitalocean', 's3'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this storage space',
            placeholder: 'My Files',
          },
          {
            name: 'location',
            label: 'Region',
            type: 'select',
            required: false,
            tier: 'essential',
            description: 'Pick the region closest to your users',
            default: 'nyc3',
            optionDetails: [
              { value: 'nyc3', label: 'New York (NYC3)', description: 'US East', provider: 'digitalocean' },
              { value: 'sfo3', label: 'San Francisco (SFO3)', description: 'US West', provider: 'digitalocean' },
              { value: 'ams3', label: 'Amsterdam (AMS3)', description: 'Europe', provider: 'digitalocean' },
              { value: 'sgp1', label: 'Singapore (SGP1)', description: 'Asia Pacific', provider: 'digitalocean' },
              { value: 'fra1', label: 'Frankfurt (FRA1)', description: 'Europe', provider: 'digitalocean' },
              { value: 'syd1', label: 'Sydney (SYD1)', description: 'Australia', provider: 'digitalocean' },
            ],
          },
        ],
      },
      {
        id: 'file-storage',
        name: 'File Storage',
        description: 'Network file system for shared access',
        icon: 'Folder',
        category: 'storage',
        behavior: 'stateful' as NodeBehavior,
        providers: ['aws', 'gcp', 'azure'],
        implementations: [
          { provider: 'aws', resource_type: 'aws:efs:FileSystem', display_name: 'EFS File System' },
          { provider: 'gcp', resource_type: 'gcp:filestore:Instance', display_name: 'Filestore' },
          {
            provider: 'azure',
            resource_type: 'azure:storage:FileShare',
            display_name: 'Azure Files',
          },
        ],
        keywords: ['efs', 'nfs', 'file', 'filestore', 'shared'],
        properties: [
          {
            name: 'name',
            label: 'Name',
            type: 'string',
            required: true,
            tier: 'essential',
            description: 'A friendly name for this shared drive',
            placeholder: 'Shared Files',
          },
          {
            name: 'size',
            label: 'Throughput mode',
            type: 'select',
            required: true,
            tier: 'essential',
            description: 'Performance tier — determines throughput and IOPS',
            default: 'efs-bursting',
            optionDetails: [
              {
                value: 'efs-bursting',
                label: 'EFS Bursting',
                description: 'Standard throughput · scales with size',
                cost: '~$0.30/GB/mo',
                provider: 'aws',
              },
              {
                value: 'efs-elastic',
                label: 'EFS Elastic',
                description: 'Auto-scaling throughput · pay per use',
                cost: '~$0.04/GB read',
                provider: 'aws',
              },
              {
                value: 'efs-provisioned',
                label: 'EFS Provisioned',
                description: 'Guaranteed throughput · predictable perf',
                cost: '~$6/MB/s/mo',
                provider: 'aws',
              },
              {
                value: 'gcp-basic-hdd',
                label: 'Basic HDD',
                description: '1 TB min · cost-effective',
                cost: '~$0.20/GB/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-basic-ssd',
                label: 'Basic SSD',
                description: '2.5 TB min · low-latency',
                cost: '~$0.55/GB/mo',
                provider: 'gcp',
              },
              {
                value: 'gcp-enterprise',
                label: 'Enterprise',
                description: 'Regional HA · high throughput',
                cost: '~$0.35/GB/mo',
                provider: 'gcp',
              },
              {
                value: 'azure-standard',
                label: 'Standard (GPv2)',
                description: 'HDD-backed · cost-effective',
                cost: '~$0.06/GB/mo',
                provider: 'azure',
              },
              {
                value: 'azure-premium',
                label: 'Premium',
                description: 'SSD-backed · low-latency',
                cost: '~$0.16/GB/mo',
                provider: 'azure',
              },
            ],
          },
        ],
      },
    ],
  };
