/**
 * Live-test helpers (developer tool, NOT CI).
 *
 * Provides:
 *   - `awsLive` / `azureLive`     skip-aware describe wrappers
 *   - `uniqueAwsName` / `uniqueAzureName`  per-service name generators
 *   - `createAwsDeployer` / `createAzureDeployer`  initialised deployers
 *   - `JsonlLogger`               appends LiveEvents to e2e/.../runs/<runId>.jsonl
 *   - `runId()`                   stable id for the whole vitest invocation
 *
 * Required env (or test skips with banner):
 *   AWS:   AWS_REGION + credentials via AWS SDK chain (AWS_PROFILE, etc.)
 *   Azure: AZURE_SUBSCRIPTION_ID + AZURE_LOCATION + credentials via
 *          DefaultAzureCredential chain (az login, service-principal env, etc.)
 *
 * Tag every resource you create with `ice:test-run-id=<runId()>` so
 * `e2e/<provider>-deployment-tests/cleanup-orphans.ts` can sweep leaks.
 */

import { appendFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { describe } from 'vitest';
import { AWSDeployer, create_aws_deployer } from '../../aws-deployer';
import { AzureDeployer, create_azure_deployer } from '../../azure-deployer';
import type { LiveEvent, LiveEventInput, LiveProvider } from './_live-types';

// ─── runId ─────────────────────────────────────────────────────────────────

const RUN_ID = (() => {
  const ymd = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  return `${ymd}-${randomBytes(4).toString('hex')}`;
})();

const RAND_SUFFIX = randomBytes(4).toString('hex');

export function runId(): string {
  return RUN_ID;
}

export const TEST_RUN_TAG_KEY = 'ice:test-run-id';
export function testRunTagValue(): string {
  return RUN_ID;
}

// ─── env gates ─────────────────────────────────────────────────────────────

const AWS_BANNER =
  'set AWS_REGION (and provide AWS credentials via AWS_PROFILE, AWS_ACCESS_KEY_ID/SECRET, SSO, or instance metadata)';
const AZURE_BANNER =
  'set AZURE_SUBSCRIPTION_ID + AZURE_LOCATION (and provide credentials via az login, service-principal env, or managed identity)';

function awsEnvOk(): boolean {
  return !!process.env.AWS_REGION;
}

function azureEnvOk(): boolean {
  return !!process.env.AZURE_SUBSCRIPTION_ID && !!process.env.AZURE_LOCATION;
}

/**
 * describe-wrapper for AWS live tests. Skips with a banner if env is missing.
 *
 * Vitest reports the skipped suite by name, so the banner is visible in
 * `pnpm test:live:aws` output — the developer immediately sees what to export.
 */
export function awsLive(name: string, fn: () => void): void {
  if (!awsEnvOk()) {
    describe.skip(`${name} [skipped — ${AWS_BANNER}]`, fn);
    return;
  }
  describe(name, fn);
}

export function azureLive(name: string, fn: () => void): void {
  if (!azureEnvOk()) {
    describe.skip(`${name} [skipped — ${AZURE_BANNER}]`, fn);
    return;
  }
  describe(name, fn);
}

// ─── name generators ───────────────────────────────────────────────────────

function trim(name: string, max: number): string {
  return name.length <= max ? name : name.slice(0, max);
}

/**
 * AWS resource name with the standard ICE test shape:
 *   `ice-test-<service>-<runId>-<rand>` trimmed to `maxLen`.
 *
 * Per-service AWS limits to pass:
 *   S3 bucket:      63
 *   Lambda fn:      64
 *   IAM role:       64
 *   SQS queue:      80 (160 with .fifo suffix)
 *   SNS topic:      256
 *   DynamoDB table: 255
 *   RDS db id:      63 (lowercase only — caller must lowercase)
 *   ECS service:    255
 *   ELBv2 LB:       32
 *   CloudFront ID:  generated by AWS; name not user-supplied
 *   CloudWatch lg:  512
 */
export function uniqueAwsName(service: string, maxLen = 64): string {
  return trim(`ice-test-${service}-${RUN_ID}-${RAND_SUFFIX}`, maxLen);
}

/**
 * Azure resource name. Tighter limits than AWS. For services like Storage
 * Accounts (3-24 chars, lowercase alphanumeric only), pass maxLen = 24 and
 * the caller should know to lowercase + strip non-alphanumeric.
 *
 * For most ARM resources, names allow dashes and 64+ chars; use default.
 *
 * Per-service Azure limits to pass:
 *   Storage Account:  24 (alphanumeric lowercase only)
 *   Key Vault:        24
 *   Function App:     60
 *   App Service:      60
 *   Cosmos DB:        50
 *   SQL Server:       63
 *   Postgres flex:    63
 *   VM:               64
 *   VNet:             64
 *   Resource group:   90
 */
export function uniqueAzureName(service: string, maxLen = 64): string {
  return trim(`ice-test-${service}-${RUN_ID}-${RAND_SUFFIX}`, maxLen);
}

/**
 * Storage-account-flavour name: lowercase, alphanumeric only, max 24.
 */
export function uniqueAzureStorageName(prefix = 'sa'): string {
  const compact = `icet${prefix}${RUN_ID.replace(/-/g, '').slice(-8)}${RAND_SUFFIX.slice(0, 4)}`.toLowerCase();
  return trim(compact, 24);
}

// ─── deployer factories ────────────────────────────────────────────────────

export async function createAwsDeployer(): Promise<AWSDeployer> {
  const region = process.env.AWS_REGION!;
  const deployer = create_aws_deployer();
  await deployer.initialize({ regions: [region] });
  return deployer;
}

export interface AzureLiveContext {
  deployer: AzureDeployer;
  subscription: string;
  location: string;
  resourceGroup: string;
}

/**
 * Azure live tests need an existing test resource group. The developer
 * creates it once:
 *
 *   az group create --name ice-test-rg --location <AZURE_LOCATION>
 *
 * Each test tags resources with `ice:test-run-id=<runId>` so
 * `cleanup-orphans.ts` can sweep leaks without nuking unrelated state.
 */
export function azureTestResourceGroup(): string {
  return process.env.AZURE_TEST_RESOURCE_GROUP || 'ice-test-rg';
}

export async function createAzureDeployer(): Promise<AzureLiveContext> {
  const subscription = process.env.AZURE_SUBSCRIPTION_ID!;
  const location = process.env.AZURE_LOCATION!;
  const resourceGroup = azureTestResourceGroup();
  const deployer = create_azure_deployer();
  await deployer.initialize({
    subscriptions: [subscription],
    resource_groups: [resourceGroup],
    regions: [location],
  });
  return { deployer, subscription, location, resourceGroup };
}

// ─── JSONL logger ──────────────────────────────────────────────────────────

const E2E_AWS_RUNS = resolve(process.cwd(), 'e2e/aws-deployment-tests/runs');
const E2E_AZURE_RUNS = resolve(process.cwd(), 'e2e/azure-deployment-tests/runs');

export class JsonlLogger {
  private path: string;

  constructor(handlerName: string) {
    const provider: LiveProvider = handlerName.startsWith('azure-') ? 'azure' : 'aws';
    const dir = provider === 'azure' ? E2E_AZURE_RUNS : E2E_AWS_RUNS;
    mkdirSync(dir, { recursive: true });
    this.path = resolve(dir, `${RUN_ID}.jsonl`);
  }

  log(event: LiveEventInput): void {
    const full = { ...event, runId: RUN_ID, ts: new Date().toISOString() } as LiveEvent;
    appendFileSync(this.path, JSON.stringify(full) + '\n');
  }

  /**
   * No-op — appendFileSync flushes per call. Method exists so tests can
   * call `logger.close()` symmetrically with `createAwsDeployer().cleanup()`.
   */
  close(): void {}

  getPath(): string {
    return this.path;
  }
}
