/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, '__esModule', { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip,
} = require('@prisma/client/runtime/index-browser.js');

const Prisma = {};

exports.Prisma = Prisma;
exports.$Enums = {};

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: '6.19.2',
  engine: 'c2990dca591cba766e3b7ef5d9e8a84796e47ab7',
};

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.Decimal = Decimal;

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.validator = Public.validator;

/**
 * Extensions
 */
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`);
};

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull;
Prisma.JsonNull = objectEnumValues.instances.JsonNull;
Prisma.AnyNull = objectEnumValues.instances.AnyNull;

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull,
};

/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable',
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password_hash: 'password_hash',
  avatar: 'avatar',
  organisation_id: 'organisation_id',
  onboarding_completed: 'onboarding_completed',
  onboarding_step: 'onboarding_step',
  default_provider: 'default_provider',
  default_region: 'default_region',
  completed_tours: 'completed_tours',
  preferences: 'preferences',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.OrganisationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.OrganisationMemberScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  organisation_id: 'organisation_id',
  role: 'role',
  joined_at: 'joined_at',
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  email: 'email',
  organisation_id: 'organisation_id',
  role: 'role',
  token: 'token',
  invited_by: 'invited_by',
  created_at: 'created_at',
  expires_at: 'expires_at',
  accepted_at: 'accepted_at',
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  user_id: 'user_id',
  expires_at: 'expires_at',
  created_at: 'created_at',
};

exports.Prisma.GitHubTokenScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  access_token: 'access_token',
  username: 'username',
  avatar_url: 'avatar_url',
  name: 'name',
  scope: 'scope',
  connected_at: 'connected_at',
  updated_at: 'updated_at',
};

exports.Prisma.CanvasProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  type: 'type',
  parent_id: 'parent_id',
  provider: 'provider',
  region: 'region',
  organisation_id: 'organisation_id',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_at: 'updated_at',
  pr_previews_enabled: 'pr_previews_enabled',
};

exports.Prisma.ProjectMemberScalarFieldEnum = {
  id: 'id',
  project_id: 'project_id',
  user_id: 'user_id',
  role: 'role',
  granted_by: 'granted_by',
  granted_at: 'granted_at',
};

exports.Prisma.CanvasCardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  project_id: 'project_id',
  nodes: 'nodes',
  edges: 'edges',
  viewport: 'viewport',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.EnvironmentScalarFieldEnum = {
  id: 'id',
  project_id: 'project_id',
  card_id: 'card_id',
  name: 'name',
  type: 'type',
  region: 'region',
  is_protected: 'is_protected',
  pr_number: 'pr_number',
  pr_branch: 'pr_branch',
  pr_source_repo: 'pr_source_repo',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.ProviderCredentialScalarFieldEnum = {
  id: 'id',
  organisation_id: 'organisation_id',
  provider: 'provider',
  credentials: 'credentials',
  project_id: 'project_id',
  is_connected: 'is_connected',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.CanvasDeploymentScalarFieldEnum = {
  id: 'id',
  card_id: 'card_id',
  user_id: 'user_id',
  status: 'status',
  action_type: 'action_type',
  provider: 'provider',
  region: 'region',
  environment: 'environment',
  plan: 'plan',
  results: 'results',
  summary: 'summary',
  snapshot: 'snapshot',
  duration_ms: 'duration_ms',
  error: 'error',
  pinned: 'pinned',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.DeployEventScalarFieldEnum = {
  id: 'id',
  deployment_id: 'deployment_id',
  card_id: 'card_id',
  seq: 'seq',
  type: 'type',
  payload: 'payload',
  created_at: 'created_at',
};

exports.Prisma.DeployedResourceMappingScalarFieldEnum = {
  id: 'id',
  card_id: 'card_id',
  node_id: 'node_id',
  environment: 'environment',
  resource_type: 'resource_type',
  resource_name: 'resource_name',
  provider_id: 'provider_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.BlockRequirementStatusScalarFieldEnum = {
  id: 'id',
  card_id: 'card_id',
  node_id: 'node_id',
  environment: 'environment',
  requirement_id: 'requirement_id',
  status: 'status',
  message: 'message',
  last_checked_at: 'last_checked_at',
  verified_at: 'verified_at',
  details: 'details',
};

exports.Prisma.DeployJobScalarFieldEnum = {
  id: 'id',
  deployment_id: 'deployment_id',
  status: 'status',
  attempts: 'attempts',
  max_attempts: 'max_attempts',
  error: 'error',
  started_at: 'started_at',
  completed_at: 'completed_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.DeploymentRuleScalarFieldEnum = {
  id: 'id',
  card_id: 'card_id',
  node_id: 'node_id',
  repository: 'repository',
  trigger_type: 'trigger_type',
  branch_pattern: 'branch_pattern',
  environment: 'environment',
  build_command: 'build_command',
  install_command: 'install_command',
  output_dir: 'output_dir',
  framework: 'framework',
  enabled: 'enabled',
  webhook_id: 'webhook_id',
  webhook_secret: 'webhook_secret',
  webhook_status: 'webhook_status',
  webhook_error: 'webhook_error',
  organisation_id: 'organisation_id',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.DeploymentEventScalarFieldEnum = {
  id: 'id',
  rule_id: 'rule_id',
  deployment_id: 'deployment_id',
  trigger: 'trigger',
  commit_sha: 'commit_sha',
  commit_message: 'commit_message',
  commit_author: 'commit_author',
  branch: 'branch',
  status: 'status',
  deployment_stage: 'deployment_stage',
  deployment_logs: 'deployment_logs',
  deployed_url: 'deployed_url',
  started_at: 'started_at',
  completed_at: 'completed_at',
  duration_seconds: 'duration_seconds',
  error: 'error',
};

exports.Prisma.WebhookDeliveryScalarFieldEnum = {
  id: 'id',
  delivery_id: 'delivery_id',
  event: 'event',
  processed: 'processed',
  result: 'result',
  created_at: 'created_at',
};

exports.Prisma.AiConversationScalarFieldEnum = {
  id: 'id',
  project_id: 'project_id',
  card_id: 'card_id',
  user_id: 'user_id',
  organisation_id: 'organisation_id',
  title: 'title',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

exports.Prisma.AiMessageScalarFieldEnum = {
  id: 'id',
  conversation_id: 'conversation_id',
  role: 'role',
  content: 'content',
  operations: 'operations',
  operation_count: 'operation_count',
  suggestions: 'suggestions',
  created_at: 'created_at',
};

exports.Prisma.AiAuditLogScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  organisation_id: 'organisation_id',
  intent: 'intent',
  canvas_before: 'canvas_before',
  operations: 'operations',
  raw_response: 'raw_response',
  parse_success: 'parse_success',
  schema_validation: 'schema_validation',
  deploy_dry_run: 'deploy_dry_run',
  duration_ms: 'duration_ms',
  model: 'model',
  error: 'error',
  created_at: 'created_at',
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc',
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull,
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last',
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull,
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
};

exports.Prisma.ModelName = {
  User: 'User',
  Organisation: 'Organisation',
  OrganisationMember: 'OrganisationMember',
  Invitation: 'Invitation',
  RefreshToken: 'RefreshToken',
  GitHubToken: 'GitHubToken',
  CanvasProject: 'CanvasProject',
  ProjectMember: 'ProjectMember',
  CanvasCard: 'CanvasCard',
  Environment: 'Environment',
  ProviderCredential: 'ProviderCredential',
  CanvasDeployment: 'CanvasDeployment',
  DeployEvent: 'DeployEvent',
  DeployedResourceMapping: 'DeployedResourceMapping',
  BlockRequirementStatus: 'BlockRequirementStatus',
  DeployJob: 'DeployJob',
  DeploymentRule: 'DeploymentRule',
  DeploymentEvent: 'DeploymentEvent',
  WebhookDelivery: 'WebhookDelivery',
  AiConversation: 'AiConversation',
  AiMessage: 'AiMessage',
  AiAuditLog: 'AiAuditLog',
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message;
        const runtime = getRuntime();
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message =
            'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' +
            runtime.prettyName +
            '`).';
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`;

        throw new Error(message);
      },
    });
  }
}

exports.PrismaClient = PrismaClient;

Object.assign(exports, Prisma);
